### ISSUE TITLE
Add to the docs how to extend a core entety with a many to one association

### ISSUE THREAD

**Issue by sawden** [shopware/shopware#1006]
*Explain in the docs how to extend a core entity*  
The Docs explain how to add a "ManyToManyAssociation" to the "ProductDefinition": https://docs.shopware.com/en/shopware-platform-dev-en/how-to/indepth-guide-bundle/entity-association?category=shopware-platform-dev-en/how-to/indepth-guide-bundle

But i can't find an explanation that shows how to add a "ManyToOneAssociation" to a core entity. 
After some research in the forum, I was able to find some posts with the same question, but with no answers.

I think an example in the documentation would be very useful here.

And please cover how to add a new "CONSTRAINT" to the new column in the product table.

💙

**Comment by shyim** [comment]
We are working currently on a new documentation. This will be better explained there

**Comment by almare** [comment]
It would also be nice if it's explained how delete a custom entity extensions with a many-to-one relation. (Many products/variants to one custom entity).  Currently I am not able to delete this relation somehow. The event product.deleted is too late and have not the foreign key which is needed to delete the entity. CascadeDelete() is also not working. By the way I didn't find any ManyToOne relation which uses CascadeDelete() on the product entity. On the database it doesn't work, because it breaks the inheritance. So at the moment it looks that it's impossible to me to maintain a many-to-one relation on a product with inheritance. I am open for any suggestion regarding this topic.

**Comment by shyim** [comment]
When you want to delete the relation. You can fetch the repository of the mapping definition and use the delete method with the both fk fields

**Comment by almare** [comment]
Thank you for your help, this is exactly what I did. The last question. Is this the official way to maintain the many-to-one relation?
