### ISSUE TITLE
Doubling the cart when old order is added again

### ISSUE THREAD

**Issue by djedrzejewski** [shopware/shopware#1008]
**Description** 
Hello. I met the problem with doubling the cart items, when trying to re-order previously accepted order. The problem happens only if there was/there's a promotion item in the cart. So to recreate this, you must go like this:
1. Create an promotion which is added as item to the cart
2. Make an successful order
3. Go to user orders summary page
4. Try to order again same set of items

With that steps, the quantity of the items in cart should be doubled.
Shopware version 6.1.2, but on 6.2 the problem is still present - checked the code.

**Possible Solution**  
I've found the propably reason. It comes from that, that the adding promotion item to the cart is interpreted as an error. Then, in the Checkout/Cart/CartRuleLoader.php:121 cart is saved "to not lose the errors", which is called even when we're trying to read the cart. And in this specific case of reordering, the cart is already filled up when it arrives as argument to controller which handle adding item action, so when we add items, they're doubled.

**Why I'm not fixing it by myself?**
Personally, I would propably go with checking type of error in CartRuleLoader, and then save cart or not. But to do this, I would have to copy whole code of this class with all of their private methods to the decorator, when the solution is size of about three lines? Quite bad solution. Also, I'm not sure if such construction like promotion-errors is not used somewhere else.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
