### ISSUE TITLE
Administration: Productlist only shows Prices for Page 1

### ISSUE THREAD

**Issue by PhenomEY** [shopware/shopware#1011]
In the administration section product the productlist only contains prices on page 1.
All other pages show "-" in the price column

**Comment by dominikkremer** [comment]
Could you provide a link and screenshot to the problem?

In the administration on the products page (http://localhost:8080/#/sw/product/index) I can see prices on page two.

![products](https://user-images.githubusercontent.com/4737861/90783984-0c5b3d80-e301-11ea-9552-de5be5ba5675.jpg)

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
