### ISSUE TITLE
Newsletter Recipient saving dont work as intended

### ISSUE THREAD

**Issue by Sheek44** [shopware/shopware#1012]
**Description**  
When you are editing/updating an Newsletter-Recipient via the Newsletter-Recipient-Detail page its not possible to save a value twice. E.g.: My recipients language is set to english. When you hit save after switching it to german the update is successful (network-tab also shows the request). When you now switch the language back to english and hit save your changed value wont get saved (network-tab also appears blank/ with no request).

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
