### ISSUE TITLE
Order of cms slots is inconsistent in 2col element

### ISSUE THREAD

**Issue by htuscher** [shopware/shopware#1037]
**Description**  

When using the two column cms element, the order of the slots in the designer view is correct, like in the 3 column element:

![image](https://user-images.githubusercontent.com/5076356/84780237-a4793580-afe5-11ea-97b2-8885c01039fc.png)

But if you open the view content of the category this layout is assigned to, you'll see that the order of the slots of the 3col element is correct, but the order of the slots of the 2col element are inverted (right, left):

![image](https://user-images.githubusercontent.com/5076356/84780569-03d74580-afe6-11ea-9285-b611760cd1f1.png)

![image](https://user-images.githubusercontent.com/5076356/84780578-089bf980-afe6-11ea-88b9-14e7980b1cd0.png)

**Possible Solution**  

**Additional context**  

There's no order for the relationship between `CmsSlot` and `CmsBlock`. Therefore it seems to be random in which order they are loaded.

**Comment by microf-berlin** [comment]
I can confirm the problem. Are there any solutions?
The current status is extremely confusing for shop operators.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
