### ISSUE TITLE
rulebuilder not equals condition doesnt work for Entitys

### ISSUE THREAD

**Issue by Sheek44** [shopware/shopware#1040]
**Description**  
When selecting the not equals filter in the rulebuilder you wont get any results for the search.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
