### ISSUE TITLE
Translation for tabs, blocks, sections and fields not working (theme.json)

### ISSUE THREAD

**Issue by psychorex** [shopware/shopware#1051]
**Description**  
Tab, block, section and field labels from theme.json are not translated.

**Additional context**  
When implementing a theme plugin (using shopware/development v6.2.2) and I add custom tabs, blocks, sections and fields, they are always English, even if the admin user changes the language to e.g. German.
All the lables have a "en-GB" and a "de-DE" value.

![image](https://user-images.githubusercontent.com/36609326/85127693-3aa09c00-b230-11ea-9d85-6befee9ef9f4.png)

```
[...]
"config":
    {
        "tabs":
        {
            "colors":
            {
                "label":
                {
                    "en-GB": "Colours",
                    "de-DE": "Farben"
                }
            }
        },
        "blocks":
        {
            "lightTheme":
            {
                "label":
                {
                    "en-GB": "Light theme",
                    "de-DE": "Helles Theme"
                }
            },
            "darkTheme":
            {
                "label":
                {
                    "en-GB": "Dark theme",
                    "de-DE": "Dunkles Theme"
                }
            }
        },
[...]
```

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
