### ISSUE TITLE
Variant URLs are broken

### ISSUE THREAD

**Issue by PhenomEY** [shopware/shopware#1086]
Only the Main variant gets the generated url which includes the article name for example. Every other variant gets an URL that includes the product UUid which doesnt look good (/detail/id) . 

All variants should get the generated product URL + an parameter for the variant like SW5 please 😊

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
