### ISSUE TITLE
Custom field - editing results in wrong config

### ISSUE THREAD

**Issue by pawonpawon** [shopware/shopware#1088]
**Description**  

Editing a custom field results in wrong field config in database.

1. Make a new custom field set - if needed
2 Click button 'New custom field'
3 Select checkbox (or any other type)
4 Click 'add' - the popup closes
5 Change your mind and click 'edit' on the new field.
6. Change type to something else.
7. Click 'add' again.
8. Save the custom field set.

Result: We now have a custom field that is a hybrid of the initial and the new field type. 

This gives errors and unexpected behaviors when trying to use the field.

**Possible Solution**  

Correctly update the type and the config for the field on save.

**Additional context**  

In database:
type = bool
config = {"type": "checkbox", "label": {"en-GB": "test2"}, "options": [{"label": [], "value": ""}, {"label": [], "value": ""}], "helpText": {"en-GB": null}, "placeholder": {"en-GB": null}, "componentName": "sw-field", "customFieldType": "text", "customFieldPosition": 1}

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
