### ISSUE TITLE
Hierarchy/order of theme inheritance in theme.json

### ISSUE THREAD

**Issue by wolv-dev** [shopware/shopware#1089]
**Description**  
Theme inheritance is not working as intended. The given order in theme.json will be ignored when `$source` is given in `Shopware\Core\Framework\Adapter\Twig\TemplateFinder::find()`.

**Additional context**  
Screenshot of our theme.json hierarchy:
![screenshot_2020-07-01_02](https://user-images.githubusercontent.com/4964718/86226108-7837ea00-bb8b-11ea-9020-dab3f03c3524.jpg)

Screenshot of result in debugger of queue after this code was executed. In this example `$source` = `SwagB2bPlatform`
```
$queue = $this->getNamespaceHierarchy();
        if ($source) {
            $index = array_search($source, $queue, true);

            $queue = array_merge(
                array_slice($queue, $index + 1),
                array_slice($queue, 0, $index + 1)
            );
        }
```
![screenshot_2020-07-01_01](https://user-images.githubusercontent.com/4964718/86226119-79691700-bb8b-11ea-917f-90f47bb91c4c.jpg)

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
