### ISSUE TITLE
Product Attributes inheritance (e.g. Packaging unit, weight, height, width) doesnt work

### ISSUE THREAD

**Issue by PhenomEY** [shopware/shopware#1091]
Product attribute inheritance doesnt work. In my case (SW 6.2.2) the packaging unit was defined in the main article and inheritance was enabled in the variant. The value was there but not visible in the variant. When i disabled inheritance, the value was visible

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
