### ISSUE TITLE
Country `Shipping available` option isn't handled on storefront

### ISSUE THREAD

**Issue by bystro** [shopware/shopware#1093]
**Description**  
There is a very useful `Shipping available` option for a country in admin panel.
However a SW storefront doesn't handle it at all - all active countries shows up in every address form.

**Possible Solution**  
1. Delivery address in customer registration form
Only `Shipping available` countries should show up for a country field.

2. Delivery address in create/update form - modal triggered from checkout and customer account overview pages
Only `Shipping available` countries should show up for a country field.

3. Managing addresses in customer account context - `/account/address` URL
Only `Shipping available` countries should show up for a country field when **default shipping address is updating only**.
Generally addresses abstract from address type. When customer creates or updates an address there is no flag we can use to determine which type the address refers to. As a result we don't know whether we should filter out none `Shipping available` countries or not.

There is a PR I created that makes above **somehow** https://github.com/shopware/platform/pull/1087. 
Generally it seems that approach where address abstracts from its type should be rethink in Shopware.

**Comment by bystro** [comment]
This is very important having EOG countries for a billing address and a Germany only for shipping address - for legal reasons.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
