### ISSUE TITLE
ManyToMany updating dont work

### ISSUE THREAD

**Issue by Sheek44** [shopware/shopware#1094]
**Description**  
When you are in the newsletter-recipient-detail and assign a tag to a recipient and save it it works perfectly fine. When you now try to delete tags it wont work untill you reload the page. After reloading the page the deletion works, but if you now want to assign a new tag for your recipient again you have to reaload the page again.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
