### ISSUE TITLE
theme:create skeleton twig issue

### ISSUE THREAD

**Issue by ckk90** [shopware/shopware#1096]
**Description**  
When using a derived theme created with the console, twig files are not parsed. It seems there is a case sensitive problem in theme.json of the plugin. This problem emerged when upgrading from 6.1.x to 6.2.x. with a derived theme created with 6.1.x. However, this problem seems to keep existing when deriving new themes in 6.2.2. as well.

Possibly related issue: https://github.com/shopware/platform/issues/956

**Possible Solution**  
"themetest" in the name and in the views section in the theme.json file are small caps:

  "name": "themetest",
  "author": "Author",
  "views": [
     "@Storefront",
     "@Plugins",
     "@themetest"
  ],

When capitalising the firs letter twig templates get parsed again (after flushing cache)

**Additional context**

**Comment by hurkandogan** [comment]
I saw this issue with 6.2.2 version today. I started to write my template name with a small letter. But the system creates name of the template folder with a capitalized letter. 

My Input: myTheme
Theme folder name: MyTheme

And in theme.json file, it uses my input as "name" and in "views":

"name": "myTheme",
  "author": "Shopware AG",
  "views": [
     "@Storefront",
     "@Plugins",
     "@myTheme" // if you don't change this one to the folder name, the system is not parsing any twig, style, or js files.
  ]

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
