### ISSUE TITLE
Obtain mandatory entity properties

### ISSUE THREAD

**Issue by S-M-O** [shopware/shopware#1104]
Hello,

Can someone tell me how it is possible in shopware 6.2.2 to find out the mandatory entity properties? In earlier version the console framework:schema also printed the required fields but now there are only the properties without a flag that they are mandatory. Especially for not so commonly used entities it would be nice to have an overview.

Thank you very much and best regards,
Stefan

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
