### ISSUE TITLE
Recalculation of order with "free shipping"-product

### ISSUE THREAD

**Issue by rommelfreddy** [shopware/shopware#1113]
**Description**  
After adding a product to an existing order (with a free shipping product) the shipping costs will be added.
The admin user do not have the opportunity to removes the shipping costs again.

**Steps to reproduce:**
- create a order with an product which is marked as `free shipping`
- open the order in the admin and edit it
- add a new product which is NOT marked as `free shipping` // or add a credit item // or add a custom item

The shipping costs has been added to the order.

**Possible Solution**  
Prevent the adding of shipping costs during the recalculation request, after a new product/credit/etc. has been added to the order.

**Comment by JoshuaBehrens** [comment]
Isn't it quite a feature that the administration recalculate the real case again? Your case is still a valid use case.
How would you distinguish your case from an order from the sales channel where the same would happen?

**Comment by rommelfreddy** [comment]
if the shop admin wants to give a credit, why the shipping cost should be added?
it does not make any sense.

If you need to add a debit for the customer or added an item to the order which is not in the shop system, just in a catalog, which is also "free shipping", the shipping costs will be added.
it does not make any sense.

if the shop admin wants to add the shipping cost he can add it with a custom line item, or shopware must implement something like a checkbox where the admin can select if the shipping costs will recalculated or not.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
