### ISSUE TITLE
Listing Sidebar doesnt work properly after level 3

### ISSUE THREAD

**Issue by PhenomEY** [shopware/shopware#1114]
Hello,

if you are using the sidebar in categories, the sidebar doesnt work properly at level 3.

Category case:
Bekleidung
    -> Damen
       --> Schuhe
        --> Oberteile

If you got into category Damen (Level 2), the sidebar shows every subcategory of Damen:

Bekleidung
  -> **Damen**
 --> Schuhe
     --> Oberteile

If you got one category deeper, example Oberteile, the sidebar will look like this:

Bekleidung
 ->Damen
     --> **Oberteile**

Now the subcategories of Damen are no longer visible. Only the subcategory which u are in is visible.
Thats sadly not a good experience for customers.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
