### ISSUE TITLE
Property configurable on product detail page

### ISSUE THREAD

**Issue by runelaenen** [shopware/shopware#1122]
**Description**  
Add checkboxe to the property set configuration to choose wether to show a property on the PDP. If the checkbox is not checked, the property should not be shown on the frontend.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
