### ISSUE TITLE
Replace private functions/properties with protected ones

### ISSUE THREAD

**Issue by patpilus** [shopware/shopware#1136]
**Description**  
Due to the business requirements sometimes we need to modify Shopware default logic. The most friendly way is to decorate existing Shopware services and override part of the code that need to be customized. Unfortunately most of them has a lot of logic inside private functions. 

Is there any particular reason of private functions/properties usage in such cases? Why not use `protected` ones, so that the code could be easily decorable?

Due to the above we're often forced to copy almost the whole file from Shopware vendor just to modify several lines of code (examples below).

**Examples**  
1) If we want to add routing outside of sales channel scope, then we should be able to add single value to `$whitelist` protected array field: https://github.com/shopware/storefront/blob/6.2/Framework/Routing/RequestTransformer.php#L94 in our decorator. Unfortunately this field is private so we cannot modify it... Function `isSalesChannelRequired` is private as well, so at the end we must add extra logic to `transform` public function to achieve the desired result...

2) Adjusting only single criterium in `AccountOrderPageLoader` requires to override `createCriteria` and copy/paste `getOrders` as well as `load` function due to the private visibility of `createCriteria`: https://github.com/shopware/platform/blob/6.2/src/Storefront/Page/Account/Order/AccountOrderPageLoader.php#L115. We must copy almost whole vendor class to decorator (~100 lines) to modify single line of code 😞 Protected visibility for `createCriteria` would make such code that easy:
```
    protected function createCriteria(string $customerId, Request $request): Criteria
    {
        $criteria = parent::createCritera($customerId, $request);        
        $criteria->addAssociation('whatever');

        return $criteria;
    }
```

3) Adding extended customer validation in Shopware Core `AccountService` should be easily decorable. Unfortunately it's done in private function, so we must call the custom logic outside of it...: https://github.com/shopware/core/blob/master/Checkout/Customer/SalesChannel/AccountService.php#L201

These are just 3 examples from Shopware Storefront and Core, but from what we see it's done similar way in most of services.

Please revise the services you've written and change the visibility of private functions and properties to `protected` wherever possible, so that Shopware Core/Storefront code can be easily modifiable without the need to copy whole vendor file contents.

**Comment by JoshuaBehrens** [comment]
Protected methods are not decoratable in a pattern where your decorator shares the same base class/interface and just forwards calls to the decorated service as the method is called with `$this` or `parent`. Using protected doesnt support decoration between anonymous decorators that are not aware of each other. As this just allows overriding only one can be selected as the replacement.

I guess what you are looking for is the extraction of these methods as services.

**Comment by patpilus** [comment]
@JoshuaBehrens yeah, but if I extend and decorate the base class (eg. https://github.com/shopware/platform/blob/6.2/src/Storefront/Page/Account/Order/AccountOrderPageLoader.php#L24) in my service then I'm able to add custom logic to functions with protected visibility (like in example 2). Is it right?

**Comment by uehler** [comment]
Shopware prefers private over protected methods because they can change and remove private methods without breaking your code.
The extraction of the private methods as services, as @JoshuaBehrens said, would introduce the same problem for shopware. If they want to change something they have to keep it backwards compatible.

But maybe adding some events inside the private methods would help you @patpilus

**Comment by patpilus** [comment]
@uehler events are more than welcome ;)

**Comment by JoshuaBehrens** [comment]
@patpilus yes you are able to do that. But everyone else is also able to do that. But only one of those who try.

I like the possible solution from @uehler. Event dispatching can be moved more easily.

**Comment by mitelg** [comment]
Hey @patpilus, @JoshuaBehrens @uehler 

PRs which add an event are always appreciated :blush: :+1: 

As @uehler already stated, we try to keep the public API, (and once methods are protected, they are "public" API) as small as possible.
This is not, because we want to make life harder for you, but to keep it easier for us to make changes without tons of deprecations or breaks. 
Shopware should of course be as much adjustable as possible, so events would be the best solution in this case. 
As we could not think of all the use cases you developers out there need, there are of course events missing. Here we need the help from you and creating a PR is the fastest way to get your event in the code :wink:

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
