### ISSUE TITLE
Promotion/Cms parentId of undefined

### ISSUE THREAD

**Issue by jd297** [shopware/shopware#1172]
**Description**  
Select your second language (e.g. English if you are German). Then reload the page via F5. Click on the Add button next to the language switch. This bug appears in the promotion list and cms list. Look at the attached image there is the failure...

**Possible Solution**  
I think the placeholder JS Mixin has a bug with the language state. I debugged the code and it fails right there.

**Additional context**  
_administration\Resources\app\administration\src\app\mixin\placeholder.mixin.js_
![image](https://user-images.githubusercontent.com/56673596/88076483-68a03580-cb7a-11ea-902d-12281ac17742.png)

_Google Chrome Console_
![promotion](https://user-images.githubusercontent.com/56673596/88076773-c3399180-cb7a-11ea-8a71-f35942a0c8f1.PNG)

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
