### ISSUE TITLE
Admin: Category Tree does not update all after category IDs correctly (v6.2.3)

### ISSUE THREAD

**Issue by AndreasA** [shopware/shopware#1184]
I have done some tests when moving categories in the admin interface and apparently the after category IDs are not always updated corretly. At least not all of them.

The one that is moved gets the correct new after ID.

However, the category that was following that category prior to moving the category might not be updated correctly.
This means the after category order is broken and might not be excactly how they are displayed in Storefront / provided by Store API navigation endpoints. 

Though it is easily fixable by moving the category with the wrong after category ID, this should be avoided at all if possible.

**Steps to reproduce**  

- Create 4 categories `a`, `b`, `c` and `d` on the same level in this order.
- Create 3 categories `ca`, `cb` and `cc` inside `c` in this order, so there is one more level to the categories.
- Now move category `b` inside `c` after `cb`.

This results in `b` getting the ID of category `cb` as  after category ID.

However, category `c` still references `b` as after category ID, instead of `a`.

Version: 6.2.3

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
