### ISSUE TITLE
ScheduledTask: Adjust interval etc. after it is registered and unregister option

### ISSUE THREAD

**Issue by AndreasA** [shopware/shopware#1197]
**Description**  
It would be nice to have an option to adjust task interval after it was registered without needing to edit the database directly.
Furthermore, how do I easily remove them, if they are not available anymore.

It would also be nice to disable etc. the task.

And an option to add a cronjob string would also be nice to handle some special cases, e.g. execute a task after typical shopping hours.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
