### ISSUE TITLE
Delete category set as entry point

### ISSUE THREAD

**Issue by TaiKamilla** [shopware/shopware#1199]
When you try to delete a category or subcategory that is selected as an "Entry point main navigation" on a Sales Channel
You can't but it does not tell you why, you only get a message on the browser console

![image](https://user-images.githubusercontent.com/15035750/88797331-7752a200-d1a3-11ea-9168-c76d9515d2ec.png)
![image](https://user-images.githubusercontent.com/15035750/88796692-5ccbf900-d1a2-11ea-935a-68bb32d5285c.png)
![image](https://user-images.githubusercontent.com/15035750/88796780-85ec8980-d1a2-11ea-9354-809351974b9f.png)

It makes sense that you can't delete the category, but it should at least display a message

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
