### ISSUE TITLE
Customer - Search for a specific customer is leading to hundreds of results

### ISSUE THREAD

**Issue by ghost** [shopware/shopware#1211]
**Description**  
If I serach for a customer, for example with an email address or a name then I get hundreds of result instead of only one. Second problem if I then sort the results for example by name, then this sorting is vanished when I click on the second page.

**Possible Solution**  
Make it possible to get one result and keep the sorting also when you get to the next page.

**Comment by akuehnis** [comment]
I agree that the customer search delivers to many results. In version v6.3.3.1 I can see that multiple words are connected with 'OR' instead of 'AND'. From a User perspective this is wrong, because when I look for 'Adrian Muller' I don't want to see all Adrian's and all Mullers' but only customers that contain  'Adrian' AND 'Muller'.

**Comment by rlincke** [comment]
I agree, the central search in the admin interface is in general difficult to work with and delivers quite bad results in comparison to what Shopware 5 could do. Also finding products is difficult, too many hits. This should be fixed ASAP :).

**Comment by Alphaegen** [comment]
I was wondering whether there's any update on this? What about adding a functionality where adding quotes around your search words specifically uses 'AND' and without does not?

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
