### ISSUE TITLE
Context::createDefaultContext() is marked as @internal

### ISSUE THREAD

**Issue by gearsdigital** [shopware/shopware#1245]
Hi everyone,

I wonder why `Context::createDefaultContext()` was marked as `@internal` with this [Commit](https://github.com/shopware/platform/commit/d9014f1fb8295d70fe8e4dd26f93d16bb37fbdce) by @keulinho.

This is still used in the [offical documentation](https://docs.shopware.com/en/shopware-platform-dev-en/how-to/creating-entities-dal) and imho necessary if you want (for example) to import product data using a scheduled task.

It'ld be great if anyone could provide some context about the _why_?

**Comment by keulinho** [comment]
Hey @gearsdigital,

the reason behind marking this method as internal is that it should not be necessary to use this method under normal circumstances.
Generally it should be possible to obtain a fully configured `Context` in the extension point of your plugin (most of the time, this will be own controllers, event subscriber or decorated services). 

The issue regarding `Context::createDefaultContext()` is that using that method will break some fundamental features of shopware, for example the translation or currency features, where the DAL automatically selects the needed languages or currencies for you.

By making the `Context::createDefaultContext()` internal we wanted to encourage plugin developers to pass down an context object from higher level services to lower level services. This is the best parctice and can be seen all over the cores codebase.
However what we saw was that in some plugins instead of passing the context down to the classes who need it, a default context was created instead, thus braking the features mentioned above.

The only valid use case to create a default context is when you are in a CLI context, meaning when you write your own CLI command (or scheduled task in that regard). But you should be fully aware that you need to take care of handling translations and currency for example by yourself in that case.

Another valid use case for the default context is the usage in tests of course, that was the original intent behind that method.
In the docs the method is used to not bloat the code examples.

I hope this clarifies our decision behind marking that method as `@internal`.

Kind regards
Jonas

**Comment by gearsdigital** [comment]
Thank you very much @keulinho! That's a great answer... I owe you a 🍺 or two 🍺🍺! 

Following your explantion it makes totally sense now. Glad you pointed out the riskyness of using `Context::createDefaultContext()` which I wasn't aware of...

It's probably a good Idea to write it down somewhere in the docs. I'ld say the whole `Context` thingy needs some documentation love, don't you think so?

**Comment by fussIntos** [comment]
Could one of you briefly explain how to "pass down an context" ? :) I have exactly this problem, my products and saleschannel are loaded, but I don't get the reference to my customer.

**Comment by cr-solutions** [comment]
same for me, I require the context inside 

`public function install(InstallContext $installContext)`

but don't know how to get it

**Comment by mitelg** [comment]
@cr-solutions just have a look in the `InstallContext` class :slightly_smiling_face: 

https://github.com/shopware/shopware/blob/trunk/src/Core/Framework/Plugin/Context/InstallContext.php#L29-L32

**Comment by cr-solutions** [comment]
@mitelg  👍🏻
Thanks so much
