### ISSUE TITLE
Can't extend block sw_number_field

### ISSUE THREAD

**Issue by brtsos** [shopware/shopware#1249]
**Description**  
Can't extend block sw_number_field. sw_number_field extend component sw-text-field.

**Possible Solution**  
In file:
src/Administration/Resources/app/administration/src/app/component/form/sw-number-field/sw-number-field.html.twig

should be : 
`{% block sw_number_field %}
    {% block sw_text_field %} <---- THIS SHOULD BE ADD
        <sw-contextual-field class="sw-field--number"`

**Comment by shyim** [comment]
Can you try the master branch?

**Comment by brtsos** [comment]
It's same. "sw-password-field/sw-password-field.html.twig" look good. I extended sw-text-field so its not big problem, but i thing its should look like in "sw-password-field.html".

**Comment by brtsos** [comment]
@shyim We can add this issue to Boots Day.

**Comment by shyim** [comment]
@pantrtxp :)

**Comment by pantrtxp** [comment]
@brtsos are you participating in our upcoming BoostDay? If so, please consider to create this issue [here](https://github.com/shopwareBoostDay/platform/issues). This way it would be created in our BoostDay Organization

Sunny regards
Pantrtxp

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
