### ISSUE TITLE
Set order in which discounts are applied

### ISSUE THREAD

**Issue by shopworksnl** [shopware/shopware#1251]
see support ticket https://account.shopware.com/partner/support/143138

If you apply for example two discounts in SW6 you want to set the order in which discounts are applied to because mixing fixed amount and percentage gives different results depending on which rule is handled first.

Example, first the customer wants the to be able to get a fixed discount, example 10 euro. After that another 25%. But, depending on which discount you handle first this has an impact on the final amount.

If you take 100 euro as example and first do 10 euro discount and then 25% you get 67,50 as end price. 
If you take 100 euro as example and first 25% and then 10 you get 65 as end price.

Ideally you can set the order in which rules are calculated (using numbers from 0 to highest prio and then up for less prio). Also you want to have a setting in a discount promotion that after handling this specific rule the calculation stops. If you are able to stop discount calculation you can prevent customers applying more discounts than possible. This request is similar as it is working in Magento 1.

**Comment by seansan** [comment]
Sounds very logic +1

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
