### ISSUE TITLE
"Please fill in all required fields" on too long meta description

### ISSUE THREAD

**Issue by runelaenen** [shopware/shopware#1261]
**Description**  
When the meta description of a category is too long (over 255 chars) the backend will say "Please fill in all required fields" instead of actually pointing out the problem.

**Possible Solution**  
Add client-side validation for field length on meta description field.

**Additional context**  
<img width="919" alt="Screenshot 2020-08-22 at 08 57 59" src="https://user-images.githubusercontent.com/3930922/90950820-95838900-e455-11ea-9e61-0c1e2d6ad4d9.png">
```[tasklist]
### Tasks
```

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
