### ISSUE TITLE
NEXT-10845 Thumbnails in administration

### ISSUE THREAD

**Issue by runelaenen** [shopware/shopware#1263]
**Description**  
The administration uses full product photos instead of thumbnails. When working with high quality and/or a lot of pictures, this slows down the browser to an unusable speed.

**Example**  
![Screenshot 2020-08-23 at 10 57 26](https://user-images.githubusercontent.com/3930922/90974856-73f6d000-e52f-11ea-92cc-540f66094e82.png)

**Comment by pantrtxp** [comment]
Hey @runelaenen,

we tried to reproduce this issue on our current master branch but could not reproduce it.
Do you mind checking it on the master again?

sunny regards 
Pantrtxp

**Comment by runelaenen** [comment]
Hi @pantrtxp 

The thumbnails are loaded when you refresh the page, but this still happens when you upload a new image to a product.

![Screenshot 2021-01-12 at 16 29 54](https://user-images.githubusercontent.com/3930922/104335307-8e881080-54f3-11eb-909f-c401a3dd17ef.png)

**Comment by htkassner** [comment]
Hey @runelaenen. This problem is already solved. After upload and save the thumbnails for the uploaded image are generated. The admin will then take the smallest thumbnail for the presentation in the admin. (currently 400px). Nevertheless we will evaluate if it makes sense for us to generate a smaller version for the admin in general which then will be used for listing and detail pages. But also the mentioned issue above is not more existent.
