### ISSUE TITLE
Different implementations of MaxResults for TOTAL_COUNT_MODE_NEXT_PAGES 

### ISSUE THREAD

**Issue by lw1994** [shopware/shopware#1264]
**Description**  
It looks like that the calculation of MaxResults when using TOTAL_COUNT_MODE_NEXT_PAGES differs between classes "JsonFactoryBase.php:72" (* 5 +1) and "EntitySearcher.php:177" (* 6 + 1).

JsonFactoryBase.php:
![image](https://user-images.githubusercontent.com/11135480/90978060-fb057180-e54a-11ea-98cb-c15111ff11b4.png)

EntitySearcher.php:
![image](https://user-images.githubusercontent.com/11135480/90978066-0ce71480-e54b-11ea-848e-d77ada4f263a.png)

Installed Shopware version is 6.3.0.0 stable.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
