### ISSUE TITLE
Rule Condition for flattened line items

### ISSUE THREAD

**Issue by tinect** [shopware/shopware#1270]
**Description**  
We need possibility do make promotions compatible to collections. Read more about it here. 
https://github.com/shopware/platform/pull/1203
It would be great to have similiar in core.

**Example**  
https://github.com/shopware/platform/pull/1203

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
