### ISSUE TITLE
Error by sw-colorpicker in administration:watch Modus because of wrong example 

### ISSUE THREAD

**Issue by rammi22** [shopware/shopware#1282]
**Description**

Using the example in the comment above the class definition in the `administration:watch` modus throws an error: `TypeError: invalid 'instanceof' operand type`. This occurred because of the [`zIndex` attribute definition](https://github.com/shopware/platform/blob/6728bf2bafd1dca9042888948003da308ff2e296/src/Administration/Resources/app/administration/src/app/component/form/sw-colorpicker/index.js#L19)

**Possible Solution**  

Instead `zIndex` it has to be `:zIndex`

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
