### ISSUE TITLE
l10n - Regions and currencies

### ISSUE THREAD

**Issue by barbanet** [shopware/shopware#1293]
**Description**  
I'm using Shopware for countries that doesn't contains Regions or the right currency to use as base currency.

I can collaborate with the data but I'm not sure which approach should I use to solve the problem. Can I create a migration for my project to add my currency and regions before the store setup? If not, can you point me in the right direction to push a commit with those changes/new data?

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
