### ISSUE TITLE
Sync API does not properly reject non array requests

### ISSUE THREAD

**Issue by itkfm-kretschmayer** [shopware/shopware#1307]
**Description**  
Sending a single object to the sync API (not wrapped into an array) will cause the kinda confusing error message: `array expected not a string for parameter 4` (typing the message from mind).

**Possible Solution**  
Check whether payload is an array; reply with status 400 if not the case.

**Additional context**  
Confusing because the code mentions `payload`, while `payload` is also a property of the actually sent object where `payload` also actually is an array, not a string.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
