### ISSUE TITLE
Question/Request: Session handover from API to native sessions

### ISSUE THREAD

**Issue by saibotd** [shopware/shopware#1314]
I need to handover an API "session" to the native frontend. The scenario is as follows:

1. Custom Frontend for the catalog and article details. Product information, customer login, and add to shopping cart via SalesChannel-API.
2. Cart, Checkout, Payment, etc. are linked to Shopware directly.

The problem is that I need to handover the session that is identified by `sw-context-token` to Shopware, so that Shopware "knows" the contents of my cart. The problem seems to be the same as [referenced in this forum thread](https://forum.shopware.com/discussion/69305/session-handling-headless-to-native?).

I am sure there is a way to do this relatively elegant und secure.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
