### ISSUE TITLE
Admin Product listing does not update page on url

### ISSUE THREAD

**Issue by blackgearit** [shopware/shopware#1318]
**Description**  
Seems that the product listing in admin area does not update the current page in the browser url, so when I visit a product detail and go back, the list restart always from page 1

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
