### ISSUE TITLE
Media Compact Upload V2 maxItems

### ISSUE THREAD

**Issue by sawden** [shopware/shopware#1361]
**Description**  
I am developing a CSM element that uses the "Media Compact Upload V2". 
The problem is, that it is not possible to specify a maximum number of items. 
However, this would be very useful.

**Example**  
For example a developer can use the "Media Compact Upload V2" to create a CSM image gallery element, that only allows a selection of 6 images. 

The solution could be to add a prop like 'maxItems'

Example **maxItems:6**
![6items](https://user-images.githubusercontent.com/36924392/93689262-1d989500-facd-11ea-8881-007f94125045.png)

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
