### ISSUE TITLE
Shipping method isn't saved correctly on creating Guest Order via the API

### ISSUE THREAD

**Issue by mmeester** [shopware/shopware#1366]
### Describe the bug
Hi all, I’m running into the issue that selecting a shippingmethod works until I create an order and the shippingmethod jumps back to the default shipping method:
- calling setShippingMethod({ id }) is making a PATCH request to the /context endpoint with the correct id
- the following GET request to /context shows the correct shipping method selected
- the cart is updated with the new selected shipping method
**So far, so good**
- Looking in the database in the cart table the shipping method hasn’t changed
- when calling the createOrder() method the order get’s created but with the wrong shippingmethod attached

Please have a look at this slack thread to see the whole issue: https://vuestorefront.slack.com/archives/CT7AQR695/p1599817895084300

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
