### ISSUE TITLE
Check for additional Charset in Content-Type in function fetchFile(...) in Mediaservice.php

### ISSUE THREAD

**Issue by Muraxon** [shopware/shopware#1372]
**Description**  
On Shopware there is a functionality to "import" files from an URL. In MediaService.php in function fetchFile(...) there is an identical check for the Content-Type
```if ($contentType === 'application/json')```

I am using the cpprestsdk for implementing a REST-Client. The method i am using is explicitly setting the charset zu 'utf-8'. 

So my Request-Content-Type looks like that:
```'application/json; charset=utf-8'```

Shopware now tries to get the image from the body sent, but there is only the json with the url i sent. And a file with the json gets created.
Is there any good reason to check for the Content-Type only?

I would suggest something like
```if (($contentType === 'application/json') || ($contentType === 'application/json; charset=utf-8'))```
To import it from URL only if "application/json" is allowed and set

Any other suggestions / thoughts to it?

**Comment by mitelg** [comment]
maybe instead of checking an explicit string, we could check if it contains `application/json`

**Comment by Muraxon** [comment]
Sounds good to me.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
