### ISSUE TITLE
Price fields in variant editor are non-unique

### ISSUE THREAD

**Issue by kev-ac** [shopware/shopware#1379]
**Description**  
When editing prices in the variants editor of a product the calculation between net and gross pricing is not working because of non-unique IDs. Two text fields with the same ID are found as per the javascript console. 

**Possible Solution**  

**Additional context**  

Output from JS console:
```[DOM] Found 2 elements with non-unique id #sw-price-field-gross```

```[DOM] Found 2 elements with non-unique id #sw-price-field-net```

Shopware version v6.3.1.1 Stable
Tested in current Google Chrome v85.0.4183.121

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
