### ISSUE TITLE
Notification badge showing above and user can see the notifications.

### ISSUE THREAD

**Issue by isaklafleur** [shopware/shopware#1383]
**Description**  

Notification dialogue opens on top instead below sometimes... 
![image](https://user-images.githubusercontent.com/10033653/94780522-deb9e780-03c8-11eb-84a5-f5bc12b6d602.png)

**Possible Solution**  

Maybe better to code it to force it always opens below?
**Additional context**

**Comment by isaklafleur** [comment]
If I zoom out to 80% then it displays below.. I on laptop with 15".

**Comment by zaifastafa** [comment]
This apparently also happens when you hide the search bar but you have a header in your custom page, then the bell icon shows weirdly on the top right.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
