### ISSUE TITLE
Two bugs. 1. List is not sorted by first letter, 2. Not all countries are available (still all countries is in the Country list)

### ISSUE THREAD

**Issue by isaklafleur** [shopware/shopware#1386]
**Description**  

![image](https://user-images.githubusercontent.com/10033653/94805662-0ae75f80-03ed-11eb-8432-c6d09cdd25c8.png)

**Possible Solution**  

1. Sort the Country list
2. Make sure all countries are injected correctly in the select element, Country.

**Additional context**

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
