### ISSUE TITLE
Delete Promotions disabled and Promotion codes, Preconditions, Discount not editable after order

### ISSUE THREAD

**Issue by MohammedAlasaad** [shopware/shopware#1405]
Delete Promotions is disabled on dropdown menu but enabled if we select it. And many things inside not Editable anymore 
like Promotion codes, Preconditions, Discount ... thats happen after customer place an order. so is that normal?

<img width="1062" alt="Screenshot 2020-10-08 at 21 49 55" src="https://user-images.githubusercontent.com/48674512/95506653-7a8eb900-09b0-11eb-8b92-852fe7cf14fd.png">

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
