### ISSUE TITLE
Time difference issue while adding the promotion in the listing and at the time of adding the promotion.

### ISSUE THREAD

**Issue by chakradharkr** [shopware/shopware#1407]
**Description**  
Test Environment--
-- Shopware version: Version 6.3.2.0

**Describe the bug**
On the promotion page, Added the promotion with some specific time but in the listing, the same time is not showing. Time is showing in the list as per other time zone format.

**To Reproduce**

1. Go to the marketing>promotion page.
2. Click on Add promotion.
3. Select the "valid from" and "valid until" date and input the other required detail
4. And then click on the Save button.
5.Here time Showing in the listing is different at the time of adding promotion.

**Expected behavior**
It must be same time in the listing and at the of adding promotion. And promotion should be applied in the cart as per the selected time.

**Screen recording**

[promotion.mp4.zip](https://github.com/shopware/platform/files/5363190/promotion.mp4.zip)

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
