### ISSUE TITLE
Improve loading state for image uploads

### ISSUE THREAD

**Issue by runelaenen** [shopware/shopware#1440]
**Description**  
When uploading an image, the user is left in a state that is not clear wether the image is actually uploaded or still uploaded. A loading bar with progress would be a great addition.

**Example**  
![maxresdefault](https://user-images.githubusercontent.com/3930922/96832370-f07a3200-143e-11eb-8b2d-ec6cfc2eb7bc.jpg)

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
