### ISSUE TITLE
Add Property Options on the fly from assignment form

### ISSUE THREAD

**Issue by runelaenen** [shopware/shopware#1471]
**Description**  
Make it possible to add a property option to a property group from the assignment form. It is a lot of work at this moment to switch between the Property-module and the Product-module during the creation of new products.

For example:
<img width="888" alt="Screenshot 2020-10-30 at 08 21 00" src="https://user-images.githubusercontent.com/3930922/97671609-dd8fdf00-1a88-11eb-81db-8eb6a3c965c8.png">

**Comment by JoshuaBehrens** [comment]
The challange here seems to be the fact that the language has to be the default one for a correct add.

**Comment by runelaenen** [comment]
> The challange here seems to be the fact that the language has to be the default one for a correct add.

Clicking it could open a modal which offers input fields for all languages, no?
Or first an inline form which will add it for the default language, with the option (`...` button) to open a modal.

**Comment by JoshuaBehrens** [comment]
I am neither UX designer nor saying that this is a bad idea. Just sharing my thoughts about upcoming technical conflicts :)

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
