### ISSUE TITLE
Javascript Module FormAjaxSubmitPlugin produces error

### ISSUE THREAD

**Issue by ROBJkE** [shopware/shopware#1479]
## **Description**  
Sometimes the `FormAjaxSubmitPlugin `produces this error:

![image](https://user-images.githubusercontent.com/26817419/97975993-47cabb80-1dca-11eb-9734-73da1df7d924.png)

For some reason the iterate method collects NodeLists instead of DOM elements.  
https://github.com/shopware/platform/blob/8534e78bf4028b914853f8a2d13111d30bbcd44c/src/Storefront/Resources/app/storefront/src/plugin/forms/form-ajax-submit.plugin.js#L105

The EventListener can only apply on DOM Elements so this error occures.

## **Possible Solution**  
For Fixing this i put a statement around the EventListeners that checks if `element` is a NodeList.

```
        if (this.options.submitOnChange) {
            Iterator.iterate(this._form.elements, element => {
                
                if ( NodeList.prototype.isPrototypeOf( element ) === false ) {
                    element.removeEventListener('change', onSubmit);
                    element.addEventListener('change', onSubmit);                    
                }
            });
        }
```

i don't know if this is 100% legit but it does the job.  
Maybe its better to check if `element` is a DOM Element.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
