### ISSUE TITLE
sw-text-editor: Not able to remove table button from buttonConfig

### ISSUE THREAD

**Issue by chrschdev** [shopware/shopware#1482]
**Description**  
In File:
src/Administration/Resources/app/administration/src/app/component/form/sw-text-editor/index.js

In Line 352, the buttonConfig will be added with some further buttons (tabe, codeSwitch).
This seems to be done because of the handler method, it can not be part of a default attribute of the property buttonConfig.

The condition around seems to be wrong for me. There should be tested, if the property was set, and if not, it will add these configs to the existing default value of the buttonConfig property.

Line 352:
if(this.$options.buttonConfig) 

is wrong

**Possible Solution**  
Replace Line 352 with the missing propsData, will solve the problem.
Now i am able to set an own buttonConfig without having the table as part of the configuration.

`
      if (!this.$options.propsData.buttonConfig) {
        ...
      }
`

**Additional context**  
n/a

Thanks, Chris

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
