### ISSUE TITLE
Loader runs always in promotion when click on save button without giving input.

### ISSUE THREAD

**Issue by chakradharkr** [shopware/shopware#1484]
**Description**  
Navigate to marketing > promotion, Now click on Add promotion then click on the save button without giving input. Here loader doesn't stop, it runs always.

**Possible Solution**  
Warning message should show in required field and loader should stop.

**Additional context**  

{"errors":[{"code":"c1051bb4-d103-4f74-8988-acbcafc7fdc3","status":"400","detail":"This value should not be blank.","template":"This value should not be blank.","meta":{"parameters":{"{{ value }}":"null"}},"source":{"pointer":"\/0\/translations\/2fbb5fe2e29a4d70aa5854ce7ce3e20b\/name"}}]}

![loader](https://user-images.githubusercontent.com/50448681/98332769-4c3ee080-2025-11eb-830b-497f09fb7cc4.png)

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
