### ISSUE TITLE
Sales channel price comparison: CSV renders line breaks for too long texts (6.3)

### ISSUE THREAD

**Issue by Huaba** [shopware/shopware#1485]
Hello :)

**Description**  
For the price comparison I always shortened the description to 300 characters:
```{{ product.translated.description|raw|length > 300 ? product.translated.description|raw|slice(0,300) ~ '...' : product.translated.description|raw }}|{#- -#}```

Since version 6.3 Shopware 6 renders the CSV incorrectly. All description fields longer than 200 are wrapped to a new line in the CSV. But the text is cut off correctly at the given value.

Example copied from the rendered CSV:
Line 1:
`Kaffee > Espresso|Baruli|Baruli Altenmarkter Espresso 1 kg|6,90 €|0,69 € / 100 Gramm|||6,90 €|https://bruehbaron.de/Baruli-Altenmarkter-Espresso-1-kg/PR1000022.1|Sofort verfügbar, Lieferzeit 1 - 3 Werktage|PR1000022.1|https://bruehbaron.de/media/da/b3/a8/1587105018/altenmarkter-mischung-espresso.jpg|&lt;div&gt;&lt;b&gt;&lt;br&gt;&lt;/b&gt;&lt;/div&gt;&lt;div&gt;&lt;b&gt;Mischung: &lt;/b&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;90% Arabica, 10% Robusta&amp;nbsp;&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Eignung: Perfekt für Espresso, sehr gut in Kaffee-Vollautomaten, sehr gut für Cappuccino oder Latte-Macchiato`
Line 2:
`&lt;/div&gt;&lt;div&gt;Geschmack: Espresso mit feinen fruchtigen Nuancen, Schokolade, K...|0.00|0.00|0.00
`

**Possible Solution**  
As temporary workaround i slice the description after 200 characters

**Additional context**  
Using Apache 2.4 and PHP 7.4 and Shopware 6.3.3.1

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
