### ISSUE TITLE
Sales channel price comparison: variants all have the price of the first variant (6.3.3.x)

### ISSUE THREAD

**Issue by Huaba** [shopware/shopware#1487]
**Description**  
Since 6.3 the CSV exports are broken in the variants. Set in the template is, as listee in documentation and provided templates:
`"{{ product.calculatedListingPrice.from.unitPrice|currency }}",{#- -#}`
and "Export variants as own products " is activated.

Unfortunately all variants get the price of the first variant. No matter what price is set for this variant and also no matter if the price of the variant is linked to the main product.

**Possible Solution**  
Not found any solution, all exports are broken at this time

**Additional context**  
Apache 2.4, PHP 7.4, Shopware 6.3.3.1

**Comment by monkevlar** [comment]
I am encountering the exact same problem when exporting the feed from a storefront. Would be nice if anyone from Shopware could find us a solution since all items in the variants group have the wrong price except the first one.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
