### ISSUE TITLE
Dissapearing content in CMS editor

### ISSUE THREAD

**Issue by runelaenen** [shopware/shopware#1502]
**Description**  
When editing pages in the content editor, the old content sometimes comes back after a save. This seems to be a caching issue since the new data is correctly updated and written to the database - however the Admin API returns the old data (which is not in the database anymore)... 
A cache clear (control + c in the backend) temporarily fixes the issue. This should however not be mandatory to do, and actually be 'discouraged' to be ran on a production website.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
