### ISSUE TITLE
In the admin end order details page, VAT details are showing out of window in mobile view.

### ISSUE THREAD

**Issue by chakradharkr** [shopware/shopware#1503]
**Description**  
At the admin end open the order overview page then selects the View option, Now scroll down and move to the item section. Here **"Item"** Section is not responsive. In it, **"VAT"** details are not visible in the mobile view. Some parts of **"VAT"** details are showing out of the window.

**Possible Solution**  
Order detail should be responsive.

**Additional context**  

![order1](https://user-images.githubusercontent.com/50448681/98938284-a819d580-250d-11eb-9d72-6bdd1e13cfae.jpeg)

![order2](https://user-images.githubusercontent.com/50448681/98938346-bb2ca580-250d-11eb-8cbf-6247e490382c.jpeg)

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
