### ISSUE TITLE
API does not properly reject bad API request when assigning product categories

### ISSUE THREAD

**Issue by itkfm** [shopware/shopware#1507]
**Description**
  
Sending the following “bad” PATCH-Request to `/api/v3/product/<productID`> will result in an error 500.
```json
{"categories":[{"2":{"id":"<cat1id>"},"3":{"id":"<cat2id>"}}]}
```

**Possible Solution**  
The API should properly validate the request and respond with status 400 if it doesn't match the API's expectations.

**Additional context**  
```
Argument 2 passed to Shopware\Core\Framework\Api\Converter\ApiVersionConverter::isFromFuture() must be of the type string or null, int given, called in /var/www/shopware/vendor/shopware/core/Framework/Api/Converter/ApiVersionConverter.php on line 170
```

Kinda similar to #1307

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
