### ISSUE TITLE
bug: column label for price in product listing

### ISSUE THREAD

**Issue by ZigaVukcevicDev** [shopware/shopware#1519]
Hi,

I am getting `null` instead of `Price` in column label. Please see attached.

![Screenshot 2020-11-19 at 15 21 49](https://user-images.githubusercontent.com/10107183/99678600-47dde300-2a7b-11eb-957d-7516c7062fd6.png)

Using version of Shopware: v6.3.3.1 Stable Version

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
