### ISSUE TITLE
Uninstalling a plugin should give us an option / confirmation to remove dependent plugins along with it

### ISSUE THREAD

**Issue by zaifastafa** [shopware/shopware#1534]
**Description**  
Is there a possibility or something in planning in which uninstalling a plugin also gives us the option to uninstall other plugins which "require" that plugin? Instead of manually uninstalling them one by one. 

It is helpful when we have a base/foundation plugin that has a dependency on several other plugins and we need to uninstall/reinstall it, then we have to remove all other plugins too one by one. 

**Example**  
We can have a confirmation message telling us about the dependency and let us remove them altogether.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
