### ISSUE TITLE
Add more Criteria Events

### ISSUE THREAD

**Issue by moorl** [shopware/shopware#1535]
**Description**  
Atm i need for the Storefront a Customer Criteria to add associations to my custom entities.

There is just one way: Add an extension after the Customer Entity was loaded....

It would be quite more simple to add a global criteria (for example: EntityCriteriaEvent) or some equal to the ProductCriteriaEvents.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
