### ISSUE TITLE
Add new Bootstrap breakpoint break slider execution

### ISSUE THREAD

**Issue by apomili** [shopware/shopware#1541]
**Description**  
Hi everybody, I usually extend the boostrap grid breakpoints in order to have a different behaviour between notebook and desktop full/hd like this

```
$grid-breakpoints: (
    xs: 0,
    sm: 576px,
    md: 768px,
    lg: 992px,
    xl: 1200px,
    hd: 1440px
);
```

If you add an image slider in a page you'll get this error (on full/hd screen)

```
plugin.manager.js?0b18:225 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at getKeys (cjs.js?586a:61)
    at mergeObject (cjs.js?586a:71)
    at deepmerge (cjs.js?586a:95)
    at Function.getViewportSettings (slider-settings.helper.js?eae3:22)
    at BaseSliderPlugin._getSettings (base-slider.plugin.js?6227:114)
    at BaseSliderPlugin.init (base-slider.plugin.js?6227:36)
    at BaseSliderPlugin._init (plugin.class.js?1462:56)
    at BaseSliderPlugin.Plugin (plugin.class.js?1462:29)
    at new BaseSliderPlugin (base-slider.plugin.js?6227:7)
```

**Possible Solution**  
I think the problem is here

```
        {% block base_script_breakpoints %}
            {# Register the available viewport breakpoints the window.breakpoints object #}
            <script>
                window.breakpoints = {{ shopware.theme.breakpoint|json_encode()|raw }};
            </script>
        {% endblock %}
```

A console.log of window.breakpoints
`console.log(window.breakpoints) //{xs: 0, sm: 576, md: 768, lg: 992, xl: 1200}`

I was not able to reach the  shopware.theme.breakpoint data in order to fix.

**Additional context**  
In addition the base.scss file insert a css rule for each breakpoint  like this

```
html {
    // used by viewport detection helper to determine the current viewport
    &::before {

        @include media-breakpoint-only(xs) {
            content: 'xs';
        }
        @include media-breakpoint-only(sm) {
            content: 'sm';
        }
        @include media-breakpoint-only(md) {
            content: 'md';
        }
        @include media-breakpoint-only(lg) {
            content: 'lg';
        }
        @include media-breakpoint-only(xl) {
            content: 'xl';
        }
    }
}
```

Can be fixed like this

```
html {
    // used by viewport detection helper to determine the current viewport
    &::before {

        @each $breakpoint in map-keys($grid-breakpoints) {
            @include media-breakpoint-only($breakpoint) {
                content: '#{$breakpoint}';
            }
        }
    }
}
```

**Comment by gRoberts84** [comment]
Unfortunately I am having this problem too.

Either `SliderSettingsHelper::prepareBreakpointPxValues` needs to be changed to default to an empty object if the breakpoint does not exist in the slider config, or the `*-slider.plugin.js` files need updating to build the default `options.slider.responsive` object based upon the `window.breakpoints` object.

i.e. 
```
responsive: Object.keys(window.breakpoints).reduce((breakpoints, breakpoint) => ({...breakpoints, [breakpoint]: {}}), {}),
```

As per the original issue, because the `html::before` isn't based upon the `$grid-breakpoints` variable, you need to add it in for the new breakpoints. 

```
html {
    &::before {
        @include media-breakpoint-only(xxl) {
            content: 'xl';
        }
    }
}
```

This forces `base-slider.plugin.js` to use the `xl` breakpoint when it would be attempting to use `xxl`.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
