### ISSUE TITLE
Form block settings broken

### ISSUE THREAD

**Issue by abvdveen** [shopware/shopware#1546]
In Shopware 6.3.3.1 it's impossible to override the receiver address. If you attach the layout to a pages and go to Content > Form > Settings > Receiver addresses, you can fill in an address, but it will not be saved.

Also the 'Confirmation text' is not used after submitting the form, although it can be edited here.

**Comment by heydavee** [comment]
Still a problem. Can somebody help / give some insight?

**Comment by abvdveen** [comment]
Will this be fixed at all?

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
