### ISSUE TITLE
API-Parameter 'page' not considered for association

### ISSUE THREAD

**Issue by bestit-ewieser** [shopware/shopware#1548]
When trying to load a paginated product listing for a specific category over the saleschannel-api, the 'page' parameter is not respected.

/sales-channel-api/v3/category/a5c1ab2466974a8ea82fec3f275b4537?associations[products][limit]=24&associations[products][page]=2

We traced the problem down to the following query in the EntityReader.php where no offset-parameter is set, only the limit.

https://github.com/shopware/platform/blob/dad2dd6feffb6eb4a0d4a8ef1ef12ca8bd7f3e46/src/Core/Framework/DataAbstractionLayer/Dbal/EntityReader.php#L712

We think the query should be extended to this:
```
                $query->innerJoin(
                $root,
                '(' . $limitQuery . ')',
                'counter_table',
                str_replace(
                    array_keys($params),
                    array_values($params),
                    'counter_table.#source_column# = #table#.#source_column# AND
                     counter_table.#reference_column# = #table#.#reference_column# AND
                     counter_table.id_count > :offset AND
                     counter_table.id_count <= (:limit + :offset)'
                )
            );
            $query->setParameter('limit', $fieldCriteria->getLimit());
            $query->setParameter('offset', $fieldCriteria->getOffset());
```

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
