### ISSUE TITLE
Filtering product listing incorrect

### ISSUE THREAD

**Issue by abvdveen** [shopware/shopware#1551]
When using the filterpanel in the product listing on the frontend, the last checked/unchecked option is not taken into account. 

For example: if I select (check) four manufacturers in the manufacturer filter, you'll see a correct GET request in the network tab of the browser, incorporating the four checked manufacturers:

https://blabla.hypernode.io/widgets/cms/navigation/fce8cf8062c5453097c77b2b818a4102?manufacturer=723d108ecae244f8b03a0cb9a046bbd7%7Cebab109a432b4446bb5c7f87fe70ebc4%7C204b2a2b2fba4c7dbab1c425cb0cb1f3%7C10357b3928f145499cf8b2d184d98561&no-aggregations=1&p=1&slots=ea6128cfcded49a29ff56a8429626422

However, when closing the filtertab to see the result, you'll see this GET request:

https://blabla.hypernode.io/widgets/cms/navigation/fce8cf8062c5453097c77b2b818a4102/filter?manufacturer=723d108ecae244f8b03a0cb9a046bbd7%7Cebab109a432b4446bb5c7f87fe70ebc4%7C10357b3928f145499cf8b2d184d98561&only-aggregations=1&reduce-aggregations=1&slots=ea6128cfcded49a29ff56a8429626422

Missing the manufacturer that was last checked and thus rendering wrong result. When you re-open the filterpanel, you'll see 3 checked manufacturers, instead of 4.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
