### ISSUE TITLE
Missing/incorrect check for options after Migration

### ISSUE THREAD

**Issue by novalis111** [shopware/shopware#1554]
There is a check if a product has options or not in the below linked line, but imho $product->getOptions never gets null, and so this check will never return true. This leads to an exception in the final return statement, when count($product->getOptionIds()) expands to count(null): 

> Parameter must be an array or an object that implements Countable

https://github.com/shopware/platform/blob/5cd13708586bdef84043a2b4601cfef37bef0a61/src/Core/Content/Product/SalesChannel/Listing/ProductListingFeaturesSubscriber.php#L394

As $product->getOptions() always returns an array, the check should be done on $product->getOptionIds() or both:

`
if ($product->getOptions() === null || $product->getOptionIds() === null) {
    return true;
}
`

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
