### ISSUE TITLE
Dynamic Product Group (Product Stream) CustomField Filters do not work

### ISSUE THREAD

**Issue by leohilbert** [shopware/shopware#1558]
**Description**  
When creating a Dynamic Group for products in Shopware you have the option to add conditions for Customfields in the Condition-Builder. However these selected fields lead to the resulting search-query to fail with a bad request
`Field \"XXX\" in entity \"product\" was not found.`
This is because the "customFields."-prefix is missing in the resulting search

**Possible Solution**  
From what I found the customFields are added to the selectbox here:
https://github.com/shopware/platform/blame/master/src/Administration/Resources/app/administration/src/module/sw-product-stream/component/sw-product-stream-field-select/index.js#L60

My idea for a fix would be to simply add "customFields." as a prefix for these values, but I'm not sure if there are any obvious side-effects that I'm not seeing here.

**Additional context**  
<img width="1308" alt="Bildschirmfoto 2020-12-14 um 12 43 14" src="https://user-images.githubusercontent.com/2004063/102077725-0afed500-3e0a-11eb-8224-ca396b08c4db.png">
<img width="1901" alt="Bildschirmfoto 2020-12-14 um 12 43 41" src="https://user-images.githubusercontent.com/2004063/102077719-0803e480-3e0a-11eb-906d-4fcb1bfb0094.png">

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
