### ISSUE TITLE
SCSS compiler fails when there are too many saleschannels

### ISSUE THREAD

**Issue by maxzirps** [shopware/shopware#1560]
**Description**  
The dependency `scssphp` has a (bad) check for an infinite calling loop:

```php
        if (count($this->callStack) > 25000) {
            // not displayed but you can var_dump it to deep debug
            $msg = $this->callStackMessage(true, 100);
            $msg = "Infinite calling loop";

            $this->throwError($msg);
        }
```

If you have many saleschannels and many scss files the call stack is exceeded when trying to change the theme of all saleschannels, since it compiles it for each channel.

Updating a plugin also fails, since it also recompiles the theme for alle saleschannels.

Current workaround is to either increase the callStack size or compile the theme one by one.

**Possible Solution**  
Only compile the theme if it hasn't already been compiled.

**Additional context**  
Shopware Version: 6.3.4

**Comment by stof** [comment]
scssphp had a bug regarding the managing of the call stack, where it would leak some frames after they are completed when using `@return`, making it much more likely to hit a callstack with 25000 items even without using an infinite loop (as executing `@return` 25000 times in the whole compilation would also trigger it).
this bug has been fixed in scssphp 1.1.0 in April 2020, but shopware still uses an older version.

**Comment by AndreasA** [comment]
@stof Would the new version also fix issues where the compile times for themes in Shopware with multiple sales channels takes forever sometimes - but not always? 
From what I see there have been a lot of updates to scssphp in contrast to the version used by Shopware which is still 1.0.6 but scssphp is now 1.4.1. 
Also from what I saw there have been various fixes regarding bootstrap updates which sound really important for Shopware as it uses bootstrap.
If scssphp uses semantic versioning, I think limiting the version like this is unnecessary anyway.

**Comment by stof** [comment]
> Would the new version also fix issues where the compile times for themes in Shopware with multiple sales channels takes forever sometimes - but not always?

@AndreasA I don't know, because I don't know which issues you are talking about. I'm not using shopware myself. I'm one of the maintainers of scssphp.
However, we made a bunch of performance optimizations in 1.1.0 so maybe.

I found this issue by luck only when looking for projects depending on scssphp to see which of our extension points are being used.

> If scssphp uses semantic versioning

We do follow semantic versioning (but we consider that cases where our compiler was accepting invalid Sass inputs are not covered by backward compatibility when we fix spec compliance, as that would otherwise mean that we consider our bugs to be part of our API).
Note that in 1.4 and in the upcoming 1.5.0 release (which we are preparing and should be out in the following weeks), we are deprecating a bunch of things, in preparation for our 2.0 release

**Comment by AndreasA** [comment]
@stof Thanks for the feedback. I hope Shopware wil update soon as the version they use is really quite old already and a newer version might fix various issues including possible performance issues.

**Comment by mitelg** [comment]
related PR #1906

**Comment by stof** [comment]
https://github.com/shopware/platform/commit/b3155cd67ba6b344294d41c093b38b0b1bdc79c4 has upgraded scssphp to 1.9.0 as part of the PHP 8.1 support, so this should be fixed in the next version.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
