### ISSUE TITLE
Stateful emails

### ISSUE THREAD

**Issue by JoshuaBehrens** [shopware/shopware#1567]
**Description**  
Sending emails is crucial for a shop and shopware has a decent mail configuration. Sending an email is a very volatile process as well. The mailing limits at Outlook are pretty easy to break with all mailing templates enabled. When the limit is reached the email is bounced and therefore lost in the void. The customer will get an error message and an underlying process might not continue properly. The failure rate in mailing is barely handled within shopware. Having a mailing queue that enables automatically resending, relays on bumps or failures, can be processed in the background without the business processes to fail. This will also allow to check whether sending an email has been successful for everyone without access to the outbox of the mailing account.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
