### ISSUE TITLE
Sender configuration for each mailing template

### ISSUE THREAD

**Issue by JoshuaBehrens** [shopware/shopware#1568]
**Description**  
I have cases where different mailers shall be used depending on the mailing template. I can imagine shared configurations that might also be used depending on the connected storefront. Having shared mail configurations also adds better support for more customized mailing setups

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
