### ISSUE TITLE
Encrypted mailing

### ISSUE THREAD

**Issue by JoshuaBehrens** [shopware/shopware#1569]
**Description**  
Some of our customers like to have encrypted mails from the shop system to their mailing. Adding this feature via plugin was do-able but heavily relies on the implementation details. Maybe the upcoming system can have a mail signature management.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
