### ISSUE TITLE
Cannot create a product without the "net" value, even if tax exists.

### ISSUE THREAD

**Issue by azngeek** [shopware/shopware#1570]
**Description**  

When creating a product, the net-value is required even if there is a tax associated with it.

**Possible Solution**  

Make the 'net' attribute optional if the tax is given.

**Additional context**  

Assume this is the operation for a new product.

- If the tax i in the payload, why does the net value needs to be set?

```
 $operation = new SyncOperation(
            'write',
            'product',
            SyncOperation::ACTION_UPSERT,
            [
                [
                    'name' => 'Testproduct',
                    'productNumber' => Uuid::randomHex(),
                    'stock' => 1,
                    'tax' => ['name' => 'tax reduced', 'taxRate' => 16],
                    'manufacturer' => ['name' => 'test'],
                    'price' => [['currencyId' => Defaults::CURRENCY, 'gross' => 10, 'net' => 0, 'linked' => true]],
                ],
            ],
            PlatformRequest::API_VERSION
        );
```

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
