### ISSUE TITLE
Url redirection incorrect at the time of  creating review

### ISSUE THREAD

**Issue by chakradharkr** [shopware/shopware#1575]
**Description**  
At the product page navigate to Write review, Here give the input detail and then click on login button. It shows the issue of url not found on server. Such issue found due to wrong url generation.

**Possible Solution**  
When click on login button then user should be easily logged in.

**Additional context**  
please check the attached video

https://www.loom.com/share/ece263c898e44320a152cf1811f21a31

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
