### ISSUE TITLE
NEXT-13121: CustomFields for salutations

### ISSUE THREAD

**Issue by runelaenen** [shopware/shopware#1579]
**Description**  
Salutations is (one of) the only entity in core shopware that has not got a customFields property.

**Possible Solution**  
Add a CustomFields property to the Salutation entity.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
