### ISSUE TITLE
Categories Description Text Editor don't clean value

### ISSUE THREAD

**Issue by Skpe829** [shopware/shopware#1592]
**Description**  
In admin when the user log in and go to Categories. In Description Updates or create a new Category and you'll go to a a Category with a empty description you get same previous description value

**Additional context** 
1
![image](https://user-images.githubusercontent.com/15944889/104350021-b23a5f00-54d1-11eb-8de6-99feaa3d579b.png)

2
![image](https://user-images.githubusercontent.com/15944889/104350210-e746b180-54d1-11eb-8414-9eacee889645.png)

In second element when it's empty don't get blank value
![image](https://user-images.githubusercontent.com/15944889/104352616-e400f500-54d4-11eb-897b-302ab3f87479.png)

**Comment by runelaenen** [comment]
Seems to be related to https://github.com/shopware/platform/issues/1476 which was fixed in https://github.com/shopware/platform/pull/1566

The PR however only fixes the custom fields, I didn't notice it was affecting more fields.

**Comment by vogelor** [comment]
i see the same. the "custom field problem" is fixed, but not this issue.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
