### ISSUE TITLE
Hot Module Reloading does not apply SASS variable overrides

### ISSUE THREAD

**Issue by AlexBachmann** [shopware/shopware#1599]
**Description**  
As described in your [Theme Guide](https://docs.shopware.com/en/shopware-platform-dev-en/theme-guide/scss), we have the possiblity to override the default bootstrap variables in our theme.json:

```
...
"style": [
    "app/storefront/src/scss/overrides.scss", <-- Variable overrides
    "@Storefront",
    "app/storefront/src/scss/base.scss"
  ],
...
```
This solution works as expected, when compiling our theme via `./psh.phar storefront:build`, the overrides are not applied however, when compiling the theme via `./psh.phar storefront:hot`. This makes the HMR functionality quickly unusable, since changing the default bootstrap variables is very common (if you want to make changes to the default grid vor example).

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
