### ISSUE TITLE
Media library upload: handle special characters in filenames (Umlaute)

### ISSUE THREAD

**Issue by ASommer** [shopware/shopware#1605]
Issue: Currently the upload to the media library just fails when the filename contains special characters (e.g. Umlaute).

Proposition: The filenames should be renamed automatically on upload to in order to fulfill the requirements.
 (otherwise display a hint what the user can do in order to avoid frustration)

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
