### ISSUE TITLE
[FEATURE] Easier way to define custom fields with a plugin?

### ISSUE THREAD

**Issue by AndreasA** [shopware/shopware#1620]
**Description**  
Why do I need to manually create the custom fields using the repositories during plugin installation / activation etc. And clean up everything during uninstallation.
Why is it not possible to do it in a similar way for plugins as it is done for the app ssytem with a configuration file?

See: https://docs.shopware.com/en/shopware-platform-dev-en/app-system-guide/app-base-guide#custom-fields

This way shopware could also take care of cleanup, if the user decides to remove custom data.

Also the documentation regarding custom fields https://docs.shopware.com/en/shopware-platform-dev-en/developer-guide/custom-fields?category=shopware-platform-dev-en/developer-guide

mentions how to create them but not where to execute them, so they are available after plugin installation. Especially, as it uses a custom services this is not possible in all plugin lifecycle events, see also my other issue https://github.com/shopware/platform/issues/1619

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
