### ISSUE TITLE
[FEATURE] Easier way to setup mail templates and their events / triggers

### ISSUE THREAD

**Issue by AndreasA** [shopware/shopware#1621]
**Description**  
I think the title says it all. Setting up custom email templates and their events and removing them, if the user decides to do so upon a plugin uninstallation, should be easier. Sure, it can be done with the repositories but personally I think it is quite convoluted, especially, as one also has to take care of the cleanup process.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
