### ISSUE TITLE
[FEATURE] DAL Migrations diff command similar to doctrine migrations diff command to automatically create schema changes migrations

### ISSUE THREAD

**Issue by AndreasA** [shopware/shopware#1622]
**Description**  
It is not strictly necessary but it would really simplify plugin development. Just execute the command and it creates the corresponding scheme migration in the plugin.

From symfony bundle documentation: `doctrine:migrations:diff                   [diff] Generate a migration by comparing your current database to your mapping information.`

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
