### ISSUE TITLE
inheritance of extended prices can't be removed from variants

### ISSUE THREAD

**Issue by fgiering** [shopware/shopware#1626]
**Description**  
When you have a variant, which shouldn't have the extended price rules (e.b. bulk prices) of the main product and you uncheck the inheritance and click "save". The inheritance won't be removed. Next time you open the variant it's still checked.

I reproduced this issue on differnt systems with Shopware 6.3.4 and 6.3.5.0

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
