### ISSUE TITLE
CSS files/Theme missing

### ISSUE THREAD

**Issue by MarvinKlar** [shopware/shopware#163]
I installed the latest version of Shopware 6 and when I finished the installation wizard, the page get's loaded without any CSS files. The CSS classes are visible in the HTML code, but there isn't a single css file loaded. They are not missing, cause there isn't a single reference to any css file in the HTML. Am I doing anything wrong? Do I have to install a theme after the installation manually?

Thank you for your help!

**Comment by pantrtxp** [comment]
Hi @MarvinKlar, 

please check the "Storefront" Sales Channel in the Administration. In the tab "Theme" should be a theme assigned. If there isn't, you can assign the default theme manually.

Usually the theme should be assigned automatically. 
What exact version did you use, the Master branch or the 6.0.0 EA1.1 release?

Sunny regards,
Thorben Pantring

**Comment by MarvinKlar** [comment]
Hello,

thank you very much for your answer. I am unable to check the "Storefront" Sales Channel in the Administration cause my website looks like this:
![Screenshot_20190903-094524](https://user-images.githubusercontent.com/34421947/64153777-d3943100-ce2f-11e9-98a5-760858fd9ce0.jpg)

How can I determine the version? I used the download link form this site: https://www.shopware.com/de/download/#shopware-6

**Comment by pantrtxp** [comment]
The state in your screenshot is the broken Storefront, please visit kaufmansshop.marvinklar.de/admin and enter the credentials chosen during the installation to log in to the administration(this is where all the management happens)

The Storefront and the Administration are completely detached from each other.

Since you downloaded our release from shopware.com you should have installed the 6.0.0 EA1/EA1.1 (You can look this up in the administration as well in the top left corner)

**Comment by MarvinKlar** [comment]
Sorry for messing this up. When accessing the admin menu, the setup completed and now everything is working fine! Thanks!
