### ISSUE TITLE
Manufacturer relationship api endpoints are broken

### ISSUE THREAD

**Issue by ascheider** [shopware/shopware#164]
Currently the relations of the manufacturer translations are broken. It is not possible to get the language of the translation.
![image](https://user-images.githubusercontent.com/6016485/64177454-ce4eda80-ce5f-11e9-8ab6-79b5ed997a21.png)

The url: http://192.168.33.10/api/v1/product-manufacturer-translation/01bdce3f88e0420284a00f4920fa446d-2fbb5fe2e29a4d70aa5854ce7ce3e20b/language looks wrong.
![image](https://user-images.githubusercontent.com/6016485/64177580-140ba300-ce60-11e9-9cfb-6ec5ac9a2956.png)

**Comment by OliverSkroblin** [comment]
Hi @ascheider,

I recorded the error in a [ticket](https://issues.shopware.com/issues/NEXT-4846) and put it in the issue tracker. 

The url looks wrong at first but is a URL for a compound primary key.  We will look at the whole thing and work out a solution for routes with compound primary keys.

**Comment by shyim** [comment]
Still a problem?

**Comment by ascheider** [comment]
@shyim Hey, sorry for the late response. I think it is still a problem. Just tested with v6.4.5.1
Open: api/product-manufacturer/2326d67406134c88bcf80e52d9d2ecb7/translations
![image](https://user-images.githubusercontent.com/6016485/137281171-a83402c4-9e18-419d-85e1-5b53281f794c.png)
Open language link: api/product-manufacturer-translation/2326d67406134c88bcf80e52d9d2ecb7-f6e24bff200e43c4a3f52c72f27d5955/language
![image](https://user-images.githubusercontent.com/6016485/137281282-f57982e2-b7e3-4225-98af-0c9d28dbf45b.png)
you get 404 as response code

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
