### ISSUE TITLE
Automatic product number and validation error bug

### ISSUE THREAD

**Issue by ZigaVukcevicDev** [shopware/shopware#1677]
My last added product has product number SW10017. 

I am adding a new product. I see that new product number is SW10015 (**should be SW10018**). When I am trying to save it I am getting `Please fill in all required fields.` but no input fields are marked with red border. When I change product number to SW10018 and save it, product is saved.

It would be nice to have a better validation error or at least Product number input should have red border.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
