### ISSUE TITLE
In the admin end, If we try to check order details under particular customer section. Here amount is showing in Euro currency but order place in US dollar.

### ISSUE THREAD

**Issue by deepakk-webkul** [shopware/shopware#211]
Preconditions (*)

Shopware 6 with demo data installed
PHP 7.2.22
Production Mode

Steps to reproduce (*)
1. Go to frontend, Try to place an order in US Dollar.
2. After that Go to admin panel, Click on customer section > select customers who have placed an order in US dollar > select orders tab > Here order amount showing in Euro Currency. **(It should be in US Dollar)**

![Screenshot (10)](https://user-images.githubusercontent.com/50043226/65607018-77a17000-dfc9-11e9-935d-e1f273970e7f.png)

3. Now check that order details here, the amount showing in US dollar

![Screenshot (11)](https://user-images.githubusercontent.com/50043226/65606175-07461f00-dfc8-11e9-95c4-aafdf87a1b89.png)

Actual result (*)
- In order tab grid, the amount should be visible in the US dollar.

**Comment by Staff-d** [comment]
Hi @deepakk-webkul !

Thanks to your detailed bug description I could reproduce this issue and a write a fix that should be merged into the master soon.


Even though a similiar bug will still occur in the "General" tab of the customer module, which will always display "€" for the turnover of a customer. This has to do with the way the DAL aggregates prices as it does not respect their currencies yet. You can track our progress on this issue here: https://issues.shopware.com/issues/NEXT-5069  

Many thanks again for your detailed bug description and we are looking forward to more of them :tada: 

Best regards: Sebastian
