### ISSUE TITLE
Adding a root category gives them a parent_version_id

### ISSUE THREAD

**Issue by JoshuaBehrens** [shopware/shopware#242]
I added a root category in the administration and saw on database level it has no `parent_id` which is plausible but it has a `parent_version_id`. How can a non-existing parent have a version id? I know the logic of `version_id`s being always the same unless you start to create an alternating version of something but this is confusing. This might impact other parent/child aware entities.

**Comment by OliverSkroblin** [comment]
Hi @JoshuaBehrens,

this is currently still a problem which we cannot solve so easily because the `\Shopware\Core\Framework\DataAbstractionLayer\FieldSerializer\ReferenceVersionFieldSerializer` cannot check if a value is set in the corresponding field.
However, we are aware of the problem and will work out a solution.

**Comment by JoshuaBehrens** [comment]
Cool to see you guys already working on that one.

**Comment by shyim** [comment]
Still a problem?
