### ISSUE TITLE
500 status when calling enpoints in sync with sw-context-token

### ISSUE THREAD

**Issue by dipsaus9** [shopware/shopware#256]
I'm using JavaScript to fetch data from the API with a sw-context-token included. The sw-context-token I generated via the POST request on the checkout/cart endpoint. I sometimes recieve a 500 status fetching the data. The error is hard to read but it says something like: An exception occurred while executing 'INSERT INTO cart. Can anyone help me out here? This problem won't happen if the data is fetched async but will happen in a Promise.all request

https://github.com/dipsaus9/shopware-cart-error

Here is a reproduction of the issue.

**Comment by ssltg** [comment]
Hi Dennis,

we've looked into this and found the problem. Currently the Cart is tried to be written twice in some cases. This will be fixed soon. I will inform you as soon as the fix is merged to the master. If you need a fix before you can hotfix it by comment line 90 in Core/Checkout/Cart/SalesChannel/CartService.php
($this->persister->save($cart, $context);)
