### ISSUE TITLE
Installation Bug

### ISSUE THREAD

**Issue by ghost** [shopware/shopware#263]
When i want to install Shopware 6, i get this error:

Slim Application Error
The application could not run because of the following error:

Details
Type: TypeError
Message: openssl_pkey_get_details() expects parameter 1 to be resource, bool given
File: C:\xampp\htdocs\public\recovery\common\src\Service\JwtCertificateService.php
Line: 30

Whole error code: https://pastebin.com/dvHXqUUK

**Comment by keulinho** [comment]
Hey @flo2000ace,

Shopware 6 doesn't use Slim, looks like you tried to install Shopware 5? Then `shopware/shopware` would be the right repository.

Please confirm, that your bug report targets Shopware 5, then i will transfer your issue.

**Comment by keulinho** [comment]
Hey @flo2000ace,

we don't support Windows for Shopware 6.
On Windows you often run into permission issues, that probably is the underlying problem here, because we can't generate an private/public key pair.

If you are on Windows you can install the installation package inside a virtual machine or in the Windows Subsystem for Linux.
