### ISSUE TITLE
No integrity constraints in prices API

### ISSUE THREAD

**Issue by htuscher** [shopware/shopware#276]
**Description**  
If you want to sync many prices to the shop, you'll gonna use the `/api/v1/_action/sync` endpoint. 
As you don't expect your middleware system to keep track of the UUIDs of every price, an `upsert` with a clear combined key should issue an update and not create duplicate records that violate integrity constraints.

The combination of `productId x ruleId x price.currency x quantityStart x quantityEnd` should be unique.

But if you upsert multiple times e.g. 
```
[
  {
    "action": "upsert",
    "entity": "product_price",
    "payload": [
      {
        "ruleId": "334c43715fb5499d8d617118df3a30ed",
        "productId": "77ad5c06e4644d6d97741cf03a2f2b31",
        "price": [
          {
            "currencyId": "b7d2554b0ce847cd82f3ac9bd1c0dfca",
            "net": 22.0,
            "gross": 25.5,
            "linked": true
          }
        ],
        "quantityStart": 1
      }
    ]
  }
]
```

You end up having multiple price entities for the same `product x rule x quantity` which doesn't make any sense and most likely violates the underlying integrity.

**Possible Solution**  
The API should be able to have compound keys and update the correct entity on duplicate key violations.

**Comment by htuscher** [comment]
![image](https://user-images.githubusercontent.com/5076356/68226894-21c1de00-fff3-11e9-90c5-b99afcb41bda.png)

**Comment by keulinho** [comment]
Hey @hhoechtl,

upserts by a unique compound key are currently not supported. This limitation doesn't only affect the Sync api, but the underlying DataAbstractionLayer in general.

The upsert method will look for the value of teh primary key field in the payload and if it is ommitted automatically generate a new id, which leads to an insert instead of an update.

Furthermore i don't think that a unique compound key of `productId x ruleId x price.currency x quantityStart x quantityEnd` would solve this problem, as it still would be possible to write invalid data. For example you could add a price for a quantity from 1-10, and add another from 5-10, that wouldn't violate the unique key, but is nevertheless invalid.

I will create two seperate Issue Tracker tickets for both issues, were you can follow the progress individually.

**Comment by keulinho** [comment]
Here are the ticket links ro follow along:

The ticket for upsert by compound unique keys: https://issues.shopware.com/issues/NEXT-5432

The ticket for better validation for the product prices: https://issues.shopware.com/issues/NEXT-5433

Feel free to add context and comments to those issues.

I'm closing this issue for now, please follow the progress in the issue tracker.
