### ISSUE TITLE
Symfony 4.4 release broke SW6

### ISSUE THREAD

**Issue by rh-elio** [shopware/shopware#307]
**Description**  
Deleting the composer.lock in an existing project tagged to EA2 (or any other way of resolving the dependencies freshly) and running a composer install breaks Shopware.
The problem probably relates to the release of Symfony 4.4 4 days ago and a wrongly tagged version. The error you receive:
![image](https://user-images.githubusercontent.com/55780795/69531007-69dd7c00-0f73-11ea-8526-5e4fe2790eba.png)
checking the relevant classes and interfaces reveals an incompatibility. The DataCollector (part of HTTP kernel) 

Current package.json gives:
`"symfony/http-kernel": "4.3.4",`
`"symfony/twig-bundle": "4.3.4",`
checking the transient dependency between twig-bundle and twig-bridge reveals that the twig-bundle uses `^4.3`:
![image](https://user-images.githubusercontent.com/55780795/69531490-3f3ff300-0f74-11ea-88c2-3163816fe720.png)
thus installing 4.4 and breaking compatibility between the packages.

**Possible Solution**  
Fix the composer dependencies (pin to lower version or update properly).

**Additional context**  
Might be fixed in master (haven't checked), but I reckon this needs to be fixed in the tagged EA2 release as well, since it's what agencies are supposed to use for stable development - what's the policy on updating that?

**Comment by mitelg** [comment]
hey @rh-elio 
thanks for reporting this issue. I already created a PR to fix it. Should be merged soon :+1:

**Comment by pweyck** [comment]
Hi @rh-elio,

I'm sorry, but we wont fix this. because we would have to replace the tag or release a new version.

Starting with 6.1 we're going to have stable branches with patch releases, to fix these kinds of issues.

Kind regards
Patrick

**Comment by Phil23** [comment]
Hey Guys, some additional infos to this. Actually we are in the last steps of a release candidate for shopware 6 final release and everyone is just working hard to bring you the RC at the beginning of december. With that we will also publish a new production template as a pendant to the development template. This new template will give you more tools for production environments and also more control over your own dependencies and versioning. It will also be the base template for upcoming shopware release packages. So we understand, that this issue is a problem for you, but there will be a better solution in the short future. That is the reason why we won't work at a solution for EA2. We will publish a first version of the production template on GitHub in the upcoming weeks. This will just be the start and we are excited to hear your feedback once we published it on GitHub.
