### ISSUE TITLE
ESLINT_DISABLED breaks webpack

### ISSUE THREAD

**Issue by htuscher** [shopware/shopware#344]
**Description**  
If you disable eslint using the `ESLINT_DISABLED` ENV variable, webpack breaks with `No Loader specified`.

Because the resulting rule is:
```json
      {
            test: /\.m?js$/,
            exclude: /(node_modules|bower_components|vendors)/,
            use: [
                {
                    loader: 'babel-loader',
                    options: babelrc,
                },
                {},
            ],
        },
```

An empty object is not allowed here.

**Possible Solution**  
Refactoring necessary.

**Additional context**

**Comment by SebastianFranze** [comment]
Hi Hans and thank you for reporting this issue.

You are right this looks really misconfigured. Not just because it breaks the config but because it can disable lint for non development environments, too.

We already scheduled the issue. You can track the progress at:
https://issues.shopware.com/issues/NEXT-5970

**Comment by shyim** [comment]
Its fixed in the meanwhile. Tested working on master
