### ISSUE TITLE
Multiple primary keys results in Internal Server Error

### ISSUE THREAD

**Issue by almare** [shopware/shopware#377]
**Description**  
I created a many-to-many entity and added an additional price column. The many-to-many relationship is managed by the sw-entity-many-to-many-select component. If I have only 2 primary columns everything works fine. 

Than I added a data grid which loads the data from the many-to-many table with the additional price field. 
If I try to load the data I receive the following error: 
`Argument 1 passed to Shopware\Core\Framework\DataAbstractionLayer\Cache\EntityCacheKeyGenerator::getEntityContextCacheKey() must be of the type string, array given, called in /home/almare/Webserver/shopware6/platform/src/Core/Framework/DataAbstractionLayer/Cache/CachedEntityReader.php on line 90`

This issue has been mentioned in gitter but I didn't found any open issue so I open this.

**Possible Solution**  
are welcome

**Additional context**

**Comment by keulinho** [comment]
Hey @almare,

the way to go here would be to split up your many-to-many to a many-to-one to the former MappingDefinition. The mapping definitions are just an shortcut and could not be expanded with arbitrary fields. You therefore have to promote your MappingDefinition to a normal definition that handles the associations. 

An example of this would be the `ProductMediaDefinition` that is basically just a many-to-many mapping between products and media with an additional `position` and `customFields` fields.

Note that it won't be possible to directly access the other end of the many-to-many with the entity. 
So instead of `$product->getMedia()` you have to call `$product->getProductMedia()->getMedia()`.

I hope this clarifies your question.

Kind regards
Jonas

**Comment by almare** [comment]
Thank you for your fast response. I didn't mention that I already made from the association mapping entity a full qualified entity (extends EntityDefinition not MappingEntityDefinition).

It looks like that I have to switch from the sw-entity-many-to-many-select to the sw-entity-multi-select and remove the primary flags inside the definition to get this working, I am right?

**Comment by keulinho** [comment]
Yes you're right use the `sw-entity-multi-select` and give your association mapping an own id than it should work.

**Comment by almare** [comment]
This issue could be closed. Works as designed. Thank you @keulinho
