### ISSUE TITLE
Variant-Switch Frontend broken on IE/Edge

### ISSUE THREAD

**Issue by cfreak** [shopware/shopware#382]
**Description**  
Variant-Switch Frontend broken on IE/Edge, the Options-Parameter is empty and the redirect to the Selected-Option URL is not working. 

**Version** 
RC2 / RC3

**Testlink**
https://www.sognidoro.de/Ring-mit-Multi-Brillant-Sternenhimmel/35021a1.1

or 

https://sognidoro.shopwaredemo.store/test123/SW20001.1

**Additional context**  

<img width="1111" alt="Bildschirmfoto 2019-12-20 um 14 55 07" src="https://user-images.githubusercontent.com/202342/71259439-bc267880-2338-11ea-901e-08f0f9842154.png">

**Comment by tobiasberge** [comment]
Hi cfreak,

thanks for reporting this issue.

A fix for this problem is currently in code review. You can track the ticket status here: https://issues.shopware.com/issues/NEXT-6151. The fix should be shipped with the next shopware 6.1 release.

The edge browser was not getting the radio buttons (those are hidden in the document to determine which label belongs to which product variant) in a correct way when selecting them via JavaScript. Therefore the request data to get the new variant url was sometimes empty in the edge browser and the user got stuck on the same or a wrong product page.

Kind regards
Tobias

**Comment by tobiasberge** [comment]
Hi @cfreak,

the problem should be fixed in the current 6.1 version.
I will close this issue since the bug is fixed. If there are any problems feel free to open a new issue.

Best regards
Tobias
