### ISSUE TITLE
Rule builder dropdown goes outside viewport

### ISSUE THREAD

**Issue by Zyles** [shopware/shopware#386]
**Description**  

When you edit rules in the rules builder the dropdown goes outside the viewport of the browser, making it impossible to scroll through all the options.

This problem is also visible in the permissions dropdown for users.

**Possible Solution**  

The dropdown should open up where there is space, for example upwards.

**Additional context**  

![image](https://user-images.githubusercontent.com/1741593/71621079-aa14c780-2bcd-11ea-9cf5-2fb3d9d90dd3.png)

**Comment by tobiasberge** [comment]
Hi @Zyles,

thanks for reporting this issue.

This was a general problem which happened to every dropdown menu that was inside a container with limited space. It will be fixed by making the dropdown menus more dynamic, like you already suggested. When not enough space is there it will open up in the opposite direction.

The fix is in code review internally and will be in the next `6.1` patch release. You can track the ticket status here:

https://issues.shopware.com/issues/NEXT-6200

Best regards
Tobias

**Comment by tobiasberge** [comment]
Hi @Zyles,

the issue should be fixed in the current release. Dropdown menus now open up in the opposite direction when no space is available.

![image](https://user-images.githubusercontent.com/8480203/74221186-c9654100-4cb1-11ea-9ff1-1043c9cee99a.png)

Best regards
Tobias
