### ISSUE TITLE
Improvements to the usability of the Migrations Command database:migrate

### ISSUE THREAD

**Issue by AlexBachmann** [shopware/shopware#406]
**Description**  
I'd like to suggest two improvements.

1. **Be more verbose about the Migration identifier argument:** If you run the database:migrate command ONLY the Shopware\Core\Migration Migrations are being run by default. For all other Migrations, you need to specify the identifier. This is especially troublesome, since the Shopware\Storefront\Migration Migrations are excluded as well. So please be more verbose about what migrations are being run. You could for example substitute the output line "migrate Migrations" with a more verbose statement like "migrate **all** migrations that satisfy the "Shopware\Core\Migration" identifier."

2. There should be an option to really run all migrations that exist for Shopware Bundles and active Plugins. The --all flag is a little bit misleading here, since it only touches the timestamps and does not refer to the statement that all existing migrations should be run. Best case scenario: Find a better wording that clearly distinguishes between time and bundle and use the --all flag to really run them all.

**Comment by JanPietrzyk** [comment]
Hi @AlexBachmann thanks for your interest. Yes the command is indeed a little troublesome. So let me respond to your concerns:

> 1. **Be more verbose about the Migration identifier argument**

In the current master the migration command is already adjusted to use real identifiers instead of namespace constraints. Shopware core as well as Storefront migrations are no longer collected independently but use the identifier *core*, So executing "bin/console database:migrate core" (where core is the default) will include all shopware migrations.

**Adding extra info to the command is very good idea and I should not be problematic**

> 2. **There should be an option to really run all migrations that exist for Shopware Bundles and active Plugins.**

This might be a little more troublesome since this could execute the migrations in a different order than anticipated. The migrations in master are a lot more open to fine grained control  from plugin authors ([see](https://github.com/shopware/platform/blob/master/src/Docs/Resources/current/2-internals/4-plugins/080-plugin-migrations.md#advanced-migration-control)), which relies on the plugin installation and update procedure.

From my point of view the command is just a shorthand for developers to test whether a migration is working. The actual execution is left to the plugin manager and shopware installer - components that have an inherent state management.

**Changing the wording is always a good idea, do you have any suggestions?**

So far from me. Maybe you could elaborate a little bit more on your use case? Is it a dev concern or is this hindering you from putting shopware to production? Where did the need arise to execute all migrations?
