### ISSUE TITLE
Password Recover - No Success Message

### ISSUE THREAD

**Issue by cfreak** [shopware/shopware#411]
**Description**  
No success message is shown when you request a new password over /account/recover

**Possible Solution**  
show a success message

**Comment by tobiasberge** [comment]
Hi @cfreak,

actually there should always be a success message: _"We sent you a confirmation email, if the provided email address is registered."_

![image](https://user-images.githubusercontent.com/8480203/74166350-b6595f00-4c26-11ea-92b7-270bfb2fbff1.png)

However the message is generic and does not differentiate if an account/email exists or not. We implemented this behavior due to security reasons. An attacker should not be able to guess if an email exists. An error message or no message at all should only be the case if there is something wrong with the system itself.

Do you get no message at all?

Best regards 
Tobias
