### ISSUE TITLE
Allow Cookies according to Regex

### ISSUE THREAD

**Issue by Sheek44** [shopware/shopware#424]
**Description**
Its not possible to allow Cookies according to an Regex like it was possible in SW5, but for some Cookie names its impossible to allow every combination the Cookie name can have.

**Comment by Sheek44** [comment]
@MarcelSchmaeing Also, is it intended that Shopware does not delete any cookies by themself? Neither the cookies the user declines nor random Cookies?

**Comment by mnaczenski** [comment]
The shopware 6 solution won't delete any cookies - this is the intended behaviour, since shopware 6 is completely new and new plugins in the store will be checked against the cookie bar, it is not necessary to remove them automatically. Every plugin should only set their cookies and local storage after the cookie is allowed. In shopware 5 we needed a much harder solution because there are already existing plugins with a lot of cookies. It was more a solution to force everyone to use the cookie bar.

**Comment by Sheek44** [comment]
Okay, thank your for your quickresponse. And what about the regex for cookie naming e.g. for google analytics?

**Comment by mnaczenski** [comment]
The regex was added because there were many requests from plugin manufacturers. Since shopware 5 and 6 are different projects, not everything will be automatically done in shopware 6 as well. I think this implementation in shopware 6 was done before the regex solution in shopware 5. So feel free to add it as PR or else you can open a ticket in our issuetracker: issues.shopware.com
