### ISSUE TITLE
Hello Guys.......

### ISSUE THREAD

**Issue by thsekeer** [shopware/shopware#427]
i am new on shopware 6 please any one  tell me from where i can learn query of shopwere 6 and from where to get help about shopware 6 .....except documentation ....

**Comment by mitelg** [comment]
hey @thsekeer 
I assume you already know the documentation https://docs.shopware.com/en/shopware-platform-dev-en/api/admin-api :grin: 

It is probably easier for us to help, if you ask a specific question. otherwise it is quite impossible to guess what exactly your problem is :wink: 

Beside that, I recommend our [gitter channel](https://gitter.im/shopware/platform), where you can find many Shopware developer from the community. [Our forum](https://forum.shopware.com/categories/shopware-6-en) is a good place to ask questions, too.

**Comment by keulinho** [comment]
You can also find free training videos at our acadamy: https://academy.shopware.com/collections?category=english-trainings&page=2

**Comment by thsekeer** [comment]
> hey @thsekeer
> I assume you already know the documentation https://docs.shopware.com/en/shopware-platform-dev-en/api/admin-api 😁
> 
> It is probably easier for us to help, if you ask a specific question. otherwise it is quite impossible to guess what exactly your problem is 😉
> 
> Beside that, I recommend our [gitter channel](https://gitter.im/shopware/platform), where you can find many Shopware developer from the community. [Our forum](https://forum.shopware.com/categories/shopware-6-en) is a good place to ask questions, too.



> hey @thsekeer
> I assume you already know the documentation https://docs.shopware.com/en/shopware-platform-dev-en/api/admin-api 😁
> 
> It is probably easier for us to help, if you ask a specific question. otherwise it is quite impossible to guess what exactly your problem is 😉
> 
> Beside that, I recommend our [gitter channel](https://gitter.im/shopware/platform), where you can find many Shopware developer from the community. [Our forum](https://forum.shopware.com/categories/shopware-6-en) is a good place to ask questions, too.

thank you so much your value able reply...

**Comment by keulinho** [comment]
@thsekeer,

i'm closing this for now as we hope that you will find some starting point for learning shopware 6 in the links we've provided here.

If you have some concrete issues don't hesitate to open another ticket.

Kind regards
Jonas
