### ISSUE TITLE
Product rating summary is misleading due to language filter

### ISSUE THREAD

**Issue by JoshuaBehrens** [shopware/shopware#459]
**Description**  
Ratings that are language dependent suit usability as customers see readable comments in the first place. But this also currently hides the overall rating on first sight. This can be misleading as well.

![changing-review-summary](https://user-images.githubusercontent.com/1133593/72880711-aae9d680-3cff-11ea-9edc-d4f3b0bd1e8a.gif)

**Possible Solution**  
Show the rating summary always for all languages as the "Show for all languages" switch is also just a filter like the rating selection.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
