### ISSUE TITLE
Product with multiple options linking to weird URLs

### ISSUE THREAD

**Issue by Zyles** [shopware/shopware#522]
**Description**  

A product with multiple options such as "BIKINI" in the official demo.

Is linking to `/detail/cfd673f71c294a9781f1fb7feab817c5` aka not a SEO processed URL.

Same issue with "Blue sapphire salt "Sel Bleu De Perse""

**Possible Solution**  

Should SEO rewrite the URL even for variants.

**Comment by mnaczenski** [comment]
There are already SEO urls for variants: https://www.shopwaredemo.store/ADELAIDE-3/SW10154.1
Perhaps the index wasn't created properly in your demo instance. You can trigger this via console:

`php bin/console dal:refresh:index`

But it should be done in the admin too after creating the variants. With 6.2 there will be an admin module for re-indexing the products via admin.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
