### ISSUE TITLE
Payment not working with /pay Route when state is not "open"

### ISSUE THREAD

**Issue by Zwergal** [shopware/shopware#525]
**Description**  
When you call the /pay Route so a customer can pay his order, it only works if the payment state of the order is "Open". Is it in any other state, the /pay Route will not work and respond with a 204 HTTP-Code with no content.
In the Backend one can set the payment state to something like "reminded" which sends an email to the customer, if he has forgotten to pay. But this will not work anymore.

**Possible Solution**  
https://github.com/shopware/platform/blob/fb4bc791e185512bfde8cd0ea462b0cf527cf82f/src/Core/Checkout/Payment/Cart/PaymentTransactionChainProcessor.php#L99
It filters all transaction which have the payment state "open". But when this state something else like "reminded", the payment doesn't work because of the line of code above.

**Additional context**  
--

**Comment by ssltg** [comment]
Hi @Zwergal ,

thank you for your contribution.
We have created an Issue for this in our Issue Tracker: https://issues.shopware.com/issues/NEXT-7196
Until it is fixed in a future Version, you can comment the line 99 in The PaymentTransactionChainProcess if you can be sure, there is only one Transaction per Order in your System.

Greets,
Stefan

**Comment by Zwergal** [comment]
Yes, thats our work-around right now. But a core hack is never good. Hope this will be fixed in the next version. Thanks for your update on this.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
