### ISSUE TITLE
Elasticsearch index lifecycle

### ISSUE THREAD

**Issue by htuscher** [shopware/shopware#528]
**Description**  

After `bin/console es:index` has been called, it doesn't automatically create the aliases needed for the integration to work. You have to call `es:create:alias` manually. This command is flagged as "Dev only" and should therefore not be necessary to use in a production environment.

Also after you reindex, the old indizes are never deleted. Therefore there's no cleanup implemented. That does work only a couple of times until your elasticsearch cluster runs full.

**Possible Solution**  
Finalize elasticsearch index lifecycle.

**Comment by OliverSkroblin** [comment]
Hey @hhoechtl,

the alias will be generated automatically over the scheduled task. We can not create the index immediately after indexing because the indexing is done over multiple queue worker. 

The create alias task is configured to run each 5 minutes. In a production system with elastic search, you should have a cronjob which runs the scheduled tasks. 
This cron job will add the `https://github.com/shopware/platform/blob/6.1/src/Elasticsearch/Framework/Indexing/CreateAliasTask.php` to the message queue.

The task is handled by this handler: https://github.com/shopware/platform/blob/6.1/src/Elasticsearch/Framework/Indexing/CreateAliasTaskHandler.php

The workflow is decribed here:
https://docs.shopware.com/en/shopware-platform-dev-en/how-to/using-elasticsearch

**Comment by htuscher** [comment]
Hi @OliverSkroblin thanks for clarifying, but the cleanup is missing, right?

**Comment by OliverSkroblin** [comment]
Thats right @hhoechtl. I will create a ticket that we will implement a command for it

**Comment by OliverSkroblin** [comment]
Here the ticket: https://issues.shopware.com/issues/NEXT-7034

**Comment by mitelg** [comment]
@hhoechtl you probably want to use this command :wink: https://github.com/shopware/platform/blob/6.1/src/Elasticsearch/Framework/Command/ElasticsearchCleanIndicesCommand.php

@OliverSkroblin I will close the ticket, as there is already a command

**Comment by colinmurphy** [comment]
Just for reference this should be setup as a CRON. We have set this on a CRON every 15 minutes to clear the old indices :) 

Also to say if you ever need to create an alias on your dev (when your not running scheduled tasks via a CRON) if you have a look in the `elasticsearch_index_task` and copy the values for the `index` and `alias` table (after running es:create:alias) you can map them by running (assuming you are using localhost and port 9200)

`curl -X PUT "http://localhost:9200/[INDEX]/_alias/[ALIAS]?pretty"` 

and then check to see if the alias is created using

`curl -X GET "http://localhost:9200/_cat/aliases/"`

Not sure if that helps :)
