### ISSUE TITLE
framework:demodata console command options

### ISSUE THREAD

**Issue by TaiKamilla** [shopware/shopware#532]
Would be nice to have options on the `framework:demodata` command

Like the number of products, main-categories, sub-categories, etc...
Also, add an option for extra demo Sales Channels

For performance tests, this will be great to be able to simulate big stores and adjust server requirements...

Note: changing the hardcoded values from `/vendor/shopware/core/Framework/Demodata/Command/DemodataCommand.php`
to big values for the image media generator takes an unreasonable amount of RAM, this needs some optimization

**Comment by keulinho** [comment]
Hello @TaiKamilla,

this options are already built in, e.g. you can use the `-p` option to define the number of products that should be generated, or `-c` for the number of categories.

For reference you can use `bin/console framework:demodata --help` to get a full list of supported options.

Kind regards
Jonas

**Comment by TaiKamilla** [comment]
Hi @keulinho,
Thanks for your reply!
What about the amount of memory?
When creating 300K products with 2 images per product (600K images), it takes more than 60GB of RAM
I know this will take a couple of days but still, to test a production env would nice

**Comment by keulinho** [comment]
Hey @TaiKamilla,

you could try to create a `/build/media` folder in your project root directory and provide some proper demo images there that should be used (.jpg and .png is currently supported).

That way the demodata generetor will use those images, instead of generating 2 new images per product.

This assumes that image generation and not the image saving inside the Core is the major bottleneck there, but it's definitely worth the try.

Probably the number of images and file size of the images you provide in the `build/media` folder will have an impact on RAM and runtime of the command.

Will be happy if you can share some results.

Kind regards
Jonas
