### ISSUE TITLE
Extend entity (relation) without custom fields

### ISSUE THREAD

**Issue by NiklasTeich** [shopware/shopware#555]
**Description**  
I need to alter the product_category relation table with custom columns. I only see documantions on how to extend entities via "extensions" (which is not the way if i'm getting it right) or with custom fields (In my case, the product_category relation does not have the possibility to add custom field data).

- how can i add fields to entity relations (like product_category)
- how can i add this field to all relevant Shopware sections?

**Possible Solution**  

**Additional context**

**Comment by pantrtxp** [comment]
Hi @NiklasTeich 

sadly, there is no way to extend mapping tables in Shopware6.
Maybe you can explain what you want to achive here :) 

Sunny Regards
Pantrtxp

**Comment by NiklasTeich** [comment]
Hi @pantrtxp 

Thanks for your response!

My current use case is to code a custom listing sort.
This sort needs product data depending on the category.
My idea was to alter the relation table to save exactly this.
Other ideads to achieve something like that are more than welcome!

Greetings,
Niklas

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
