### ISSUE TITLE
EntityRepositoryInterface::searchIds is undecoratable

### ISSUE THREAD

**Issue by JoshuaBehrens** [shopware/shopware#585]
**Description**  
It is not possible to properly decorate `::searchIds` as `EntityRepository::search` is using `$this->searchIds`. This makes it likely to behave like undefined behaviour as one has to apply the same changes made in `::searchIds` in the decorator for `::search` as well but at a different time of state.

**Possible Solution**  
Extract logic in sub services that are used within the `EntityRepository` implementation which results in not having member method calls to functions that are defined within the interface.

**Additional context**  
https://github.com/shopware/platform/blob/fb4bc791e185512bfde8cd0ea462b0cf527cf82f/src/Core/Framework/DataAbstractionLayer/EntityRepository.php#L90

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
