### ISSUE TITLE
productRepository assign property by id

### ISSUE THREAD

**Issue by tinect** [shopware/shopware#627]
**Description**  
I tried to assign property to product by id, but name of option is required which results in a new option with same name in propertyGroup. I don't get how to assign a new property by groupId AND existing optionId. Related to #621

**Example**
```
$data = [...];
$data['properties'][] = [
    'id' => Uuid::randomHex(),
    'groupId' => $propertyGroupId,
    'optionId' => $propertyId,
    'name' => 'swag blue';
```
While optionId isn't caught, this will result new entry `swag blue` in propertyGroupOptions.

```
$data = [...];
$data['properties'][] = [
    'id' => Uuid::randomHex(),
    'groupId' => $propertyGroupId,
    'optionId' => $propertyId;
```
Which is not valid because name is required.

**Comment by tobiasberge** [comment]
Hi @tinect,

product.properties is a many to many association. If you want to link an existing entity, you only need to send the ID:
```
$data['properties'][] = ['id' => $propertyId]
``` 

Best regards
Tobias

**Comment by tinect** [comment]
Hi @tobiasberge,

Best thanks! Thought I've to create a new id for entry. This would as expected!
Thank you for this course :-)

**Comment by Sellighsphire** [comment]
Saw this and #621 and I'm not able to delete old properties, because delete only accepts a string as first parameter and therefore I thought I need the many-to-many-ID. But obviously, I can't get any ID. 
So, how do I delete a certain property from a product. 
It might also help, to delete _all_ properties from a product. In fact this will be my favourite approach.

`$prodprop = RepositoryFactory::create(ProductPropertyDefinition::ENTITY_NAME);
$crit = new Criteria();
$crit->addFilter(new EqualsFilter('productId', '24131a7285234fd7ac061c93f66c8414'));
$crit->addFilter(new EqualsFilter('optionId', '1488883f16944a66a2476e34e47d2554'));
$prod_prop_id = $prodprop->search($crit,$context)->getEntities()->first()->id;
$prodprop->delete($result,$context);

// this also doesn't work
$prodprop = RepositoryFactory::create(ProductPropertyDefinition::ENTITY_NAME);
$prodprop->delete([
	'productId' => '24131a7285234fd7ac061c93f66c8414',
	'optionId' => '1488883f16944a66a2476e34e47d2554',
],$context);`
