### ISSUE TITLE
shipping cost are not reflecting currency factors.

### ISSUE THREAD

**Issue by SangyoonKim-iotrust** [shopware/shopware#632]
**Description**  
I'm using api to developing frontend.
and I patched currency and country with post context request, and cart get request shows I`m using USD on product price.
but shipping cost is not converted to usd.
it only shows euro value.

**Possible Solution**  
I think shipping method entity doesnt have any currency convert calculate functions.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
