### ISSUE TITLE
OpenAPI code generation broken: "Attribute missing" & Broken PHP

### ISSUE THREAD

**Issue by SkaveRat** [shopware/shopware#637]
**Description**  
When trying the generate a php client, I get following error:

```
Errors: 
	-attribute components.schemas.relationshipLinks.items is missing
```

**Additional context**  
Codegen command:
```bash
openapi-generator generate -i openapi3.json -g php -o /tmp/php_api_client
```

I can deactivate the validation with `--skip-validate-spec`, but that throws several hundreds of lines of warnings, as well as generating broken PHP code.

Example using `getProduct`:

```php
$config = Configuration::getDefaultConfiguration()->setAccessToken("myAccessToken");
$api = new ProductApi(null, $config);
$api->getProduct("someId");
```

Throws following exception:
```
In ObjectSerializer.php line 326:
                                                                        
  Attempted to load class "Success" from the global namespace.          
  Did you forget a "use" statement for "OpenAPI\Client\Model\Success"? 
```

I can fix that error by changeing the affected string `'Success' ` to `Success::class`, but that just pushes the Exception to the next problem:

```
In ObjectSerializer.php line 326:
                                                            
  Attempted to load class "map" from the global namespace.  
  Did you forget a "use" statement? 
```

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
