### ISSUE TITLE
Product getName and other translatable entities do not default to default sales channel language

### ISSUE THREAD

**Issue by TheKeymaster** [shopware/shopware#689]
**Description**  
1. Create a new sales channel with only one language that none of the products have a translation yet.
1. Set the sales channel to one of these products.
1. Query the product entity with DAL.

```php
$product->getName();
// Returns null.

$product->getTranslation('name');
// Returns the translation of the default sales channel language.
```

Now assign the default sales channel language to the sales channel you have created and somehow it can find the correct translation:

```php
$product->getName();
$product->getTranslation('name');
// Both return the translation of the default sales channel language.
```

I have had a discussion on gitter with @mitelg about this. This not only affects `getName`, but also `getDescription` and generally speaking; everything that could be translated.

**Possible Solution**

These possible solutions are not mutually-exclusive. It may make sense to pick multiple to solve that issue.

1. Always fallback to the default sales channel language if the texts have not yet been translated into the respective language.
1. Add methods for always getting the respective translation. `getTranslation` with some string is not very clean and also makes typehinting much harder.
1. (not a solution but definitely helpful when debugging) Make clear that these methods will only translate the properties if the languages are actually assigned to the sales channel.

**Additional context**  
As a developer you see that Shopware in the backend will always show the translation of the default  language as placeholder. You'd expect calling the methods that would return this would also get that translation, which they aren't.

This just took much time to investigate and is hard to get into, if you are not already familiar with this issue. The thing is that on one side you see the placeholder and on the other side you need to manually call `getTranslation`, so it actually fallbacks to it? It is just a weird behavior and should be fixed.

**Comment by OliverSkroblin** [comment]
Hi @TheKeymaster,

this was a long discussed topic internally. 
We decided to use this solution because we want to use the API to output the fields in a way that you can send them back with the same value. If we would always consider inheritance under getName, this would not be the case. Therefore we have agreed on the getTranslation() solution. 

Via API the data is then available under product.translated.name.
In twig you can simply use product.translated.name.

However, I will suggest internally that the documentation should refer to this in more detail.
