### ISSUE TITLE
E-mail sent as Plain/text (Header and footer included in sales-channel)

### ISSUE THREAD

**Issue by Bogdan-Cristian** [shopware/shopware#703]
When i change the payment status from the product, the email is sent as a Plain/text, but when I send it from Email-templates it is sent like a HTML (Header and footer is included in sales-channel)

**Comment by pantrtxp** [comment]
Hi @Bogdan-Cristian,

please provide some more information. We lack the environment and steps to reproduce

Sunny regards
Pantrtxp

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
