### ISSUE TITLE
Admin - Customer-Detail - Addresses can't be changed

### ISSUE THREAD

**Issue by rasgor** [shopware/shopware#721]
The Adresses can't be saved due to:

src\Administration\Resources\app\administration\src\module\sw-customer\view\sw-customer-detail-addresses\index.js - Line 215

Problem is, that the required properties aren't availabe within the entity 'customer_address'. Therefore folling error occurs within the getRequiredProperties function.

```
TypeError: Cannot read property 'forEach' of undefined
    at Object.getRequiredProperties
```

```
isValidAddress(address) {
            const requiredAddressFields = Entity.getRequiredProperties('customer_address');
            let isValid = true;

            isValid = requiredAddressFields.every((field) => {
                return required(address[field]);
            });

            return isValid;
        },
```

**Comment by binaermanufaktur** [comment]
Thanks @rasgor for pointing this out! Here is a hotfix "plugin" that overrides the ```isValidAddress()``` function by returning true always. Makes the editing of customer adresses work:
https://github.com/binaermanufaktur/sw6-CustomerAddressHotFix

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
