### ISSUE TITLE
Not able to store documents settings

### ISSUE THREAD

**Issue by themazim** [shopware/shopware#731]
**Description**  
Not able to store documents settings when editing a document.

Can only change document name, but settings like type, show headline  and everything else cannot be changed when accessed.

This did work before, out of a sudden it does not work any longer (not even with newly created documents)

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
