### ISSUE TITLE
all documents deleted (invoice, credit, storno, delivery note)

### ISSUE THREAD

**Issue by themazim** [shopware/shopware#732]
**Description**  
all documents have been deleted for no reason. 

Did adjust all of them with working test (invoice worked 100%)

some days later, updated to 6.1.5 (2 days ago) edited some content in the meantime and just wanted to create a new invoice for a customer, which was default document with no data, checked the documents and all were gone.

I did not delete them myself.
Running 6.1.5
I do not know when exactly this happened, table was completely empty.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
