### ISSUE TITLE
content changes are reverted (i.e. shipping details, right of recission)

### ISSUE THREAD

**Issue by themazim** [shopware/shopware#733]
**Description**  
often changes, which worked 100%, also shown in the FE, change back to a previous (WTF?!) version.

This mostly happens to content changes, you change some text and it states: text saved, FE shows changes, but after a while, changes are reverted for 

**Possible Solution**  
only issue I maybe could think of, old version opened in another tab on another PC, and saved automatically over the newly edited version (autosave), so this would need to be disabled

**Additional context**  
no rollback of DB, not other scripts running, no changes by someone else.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
