### ISSUE TITLE
no footer attached to delivery status changed email

### ISSUE THREAD

**Issue by themazim** [shopware/shopware#735]
**Description**  
defined footer is not attached to delivery changed email.

**Possible Solution**  
attach footer to delivery status changed email.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
