### ISSUE TITLE
Feature request: make it possible to add media attachments through event

### ISSUE THREAD

**Issue by moorl** [shopware/shopware#742]
https://github.com/shopware/platform/blob/2b599a79d9a41d1f9dddcc34a232225594eff5e1/src/Core/Content/MailTemplate/Subscriber/MailSendSubscriber.php#L139

Use case: My customer fills up my custom contact form with attachments

I could build a workaround with direct links to media in the mail template. but as a real attachment it is even more comfortable and I can clean up my uploaded media immediatly.

**Comment by hlohaus** [comment]
In the master it is possible :)

**Comment by moorl** [comment]
hi @hlohaus 

actually the media attachments are just possible through the mail template, but not through the event itself.

https://github.com/shopware/platform/blob/master/src/Core/Content/MailTemplate/Subscriber/MailSendSubscriber.php#L119

We need something like `$mailEvent->getMedia()` :)

**Comment by hlohaus** [comment]
https://gist.github.com/hlohaus/aac10720784a198dcd283c462613e64a

Or for example you can decorate the MailService.

**Comment by moorl** [comment]
nice ty, that is maybe what I am looking for...

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
