### ISSUE TITLE
Do not create invoices if input data is not provided

### ISSUE THREAD

**Issue by themazim** [shopware/shopware#745]
**Description**  
if you click faster than shopware loads the data for the create invoice modal, an invoice without date and without proper number is created. This leads to a internal 500 if you want to open the invoice:

```
{
    errors: [
{
    code: "0",
    status: "500",
    title: "Internal Server Error",
    detail: "Return value of Shopware\\Core\\Checkout\\Document\\DocumentConfiguration::getDocumentNumber() must be of the type string or null, int returned"
}
]
}
```

**Possible Solution**  
validate fields before creating an invoice.

**Additional context**  
![image](https://user-images.githubusercontent.com/2002126/79212436-ec45da00-7e47-11ea-957e-7e011cbf8c01.png)

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
