### ISSUE TITLE
Media Element - Found 2 elements with non-unique id #files: 

### ISSUE THREAD

**Issue by ChristopherDosin** [shopware/shopware#761]
Since you're using a [hard-coded ID within the media component](https://github.com/shopware/platform/blob/e437f0416e828715810f0e5febdd793143c9137d/src/Administration/Resources/app/administration/src/app/component/media/sw-media-upload-v2/sw-media-upload-v2.html.twig#L171), you don't have unique ID's if you're using a media component more than once within the same page / component.

Therefore you will get an error if you have more than two media components.
```
Media Element - Found 2 elements with non-unique id #files: 
```
**My thought:**
What about a mixin that returns a UUID and every file input gets a `data-uuid` attribute which makes use of it instead of a hardcoded ID?

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
