### ISSUE TITLE
Make Order Transaction Change E-Mail sending configurable (optional)

### ISSUE THREAD

**Issue by oriske** [shopware/shopware#764]
**Description**  
We a building a Shopware 6 Store connected to Navision ERP for Order processing.
If changing the Order state / Delivery State in the Admin-Backend having a valid Transaction State Change E-Mail template is mandatory.

It would be nice to have sending E-Mails on order state change configurable (optional) for each template, so we can change state withour sending e-mails to customers.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
