### ISSUE TITLE
Shipping method availability check is delayed one request

### ISSUE THREAD

**Issue by htuscher** [shopware/shopware#770]
**Description**  
We have a shipping method which only becomes active if you're above 20 EUR cart value.
If I change the qty of an article in the cart and we reach that threshold, the error is still displayed.

If I change the qty again (or reload the page), the error disappears.

There seems to be something wrong in the order of events.

![](http://g.recordit.co/SeDWNTN4fU.gif)

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
