### ISSUE TITLE
checkout for non blocket rules

### ISSUE THREAD

**Issue by mhaasler** [shopware/shopware#777]
**Description**  
Order with nonBlocket Rules isn't possible
[@see ](https://github.com/shopware/platform/blob/master/src/Storefront/Resources/views/storefront/page/checkout/confirm/index.html.twig)
inside of block: `page_checkout_confirm_form_submit`

**Possible Solution**  
Change 
```
{% if page.cart.errors|length > 0 %}
  disabled
{% endif %}
```

to 

```
{% if page.cart.errors.blockOrder %}
  disabled
{% endif %}
```

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
