### ISSUE TITLE
Product availability through rule builder

### ISSUE THREAD

**Issue by htuscher** [shopware/shopware#779]
**Description**  
It would be great if we could use the rule builder to define the availability of a product.

**Example**  
* Can only be bought if article XYZ is also in cart
* Can only be ordered up until a certain date

**Comment by AndreasA** [comment]
It would be a really great feature to have this available in the Shopware core. It is possible to implement something like this relatively easily but this should be possible by default.
And it should not only be products but also categories, so one can have categories only shown e.g. if a customer is logged in.

Btw. the product entity actually has two ID list fields for rules that actually does something like this but those fields cannot be set anywhere in the admin interface and the admin interrface would also use it in its listing, so products would disappear there too as the availability rule most likely will not match in the admin interface.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
