### ISSUE TITLE
Double Css Class "product-detail-buy"

### ISSUE THREAD

**Issue by DevertNet** [shopware/shopware#795]
**Description**  
The class "product-detail-buy" was used two times.

**Possible Solution**  
Rename one of the css classes.

**Additional context**  
https://github.com/shopware/platform/blob/6.2/src/Storefront/Resources/views/storefront/page/product-detail/buy-widget.html.twig#L2
https://github.com/shopware/platform/blob/6.2/src/Storefront/Resources/views/storefront/page/product-detail/index.html.twig#L58

**Comment by wexoada** [comment]
interested

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
