### ISSUE TITLE
Tag with same name is added multiple times

### ISSUE THREAD

**Issue by marvincaspar** [shopware/shopware#798]
**Description**  
If I add tags to a product and type a new tag with the same name, it is stored multiple times. This makes it hard to create rules for dynamic product groups.

**Possible Solution**  
Make the tag name unique.

**Additional context**  
![image](https://user-images.githubusercontent.com/2600346/81211252-6135ab00-8fd3-11ea-828e-684e5c558c3c.png)

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
