### ISSUE TITLE
Switching custom field type leads to broken interface

### ISSUE THREAD

**Issue by htuscher** [shopware/shopware#801]
**Description**  
If you create a new custom field and you first choose it to be a select field and then switch to text field, it stores the property values of the select field in the JSON configuration:

```
{"type": "text", "label": {"de-DE": "Herkunftsland", "en-GB": "Country of origin"}, "options": [{"label": [], "value": ""}, {"label": [], "value": ""}], "helpText": {"en-GB": null}, "numberType": "int", "placeholder": {"en-GB": null}, "componentName": "sw-single-select", "customFieldType": "text", "customFieldPosition": 1}
```

Eventhough the `customFieldType` is `text` it's displayed as select field:

![image](https://user-images.githubusercontent.com/5076356/81264706-2880ea80-9042-11ea-990d-4eac5e049f4d.png)

And is therefore not usable. 

The only possibility you have atm is to manually fix the JSON configuration of the field in the database and clear the cache.

**Possible Solution**  

Reset the configuration if you change the field type.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
