### ISSUE TITLE
NEXT-8309 - AdminOrders: Add address to customer selection

### ISSUE THREAD

**Issue by Phil23** [shopware/shopware#814]
EN:
If you search for customers in the module, only names are displayed. Since these can now be doubled, it can be very useful to enter the address under the name in small letters, so that you can be sure to choose the right customer.

DE:
Wenn man im Modul nach Kunden sucht, bekommt man nur Namen angezeigt. Da sich diese nun doppeln können, kann es sehr sinnig sein, unter dem Namen in klein noch die Adresse anzugeben, damit man sich sicher sein kann, den richtigen Kunden auszuwählen.

**Comment by wexoaer** [comment]
Interested

**Comment by wexoaer** [comment]
@Phil23 Not directly sure, what the issue are? since the address is shown both in customer and order search?

![Screenshot from 2020-05-14 09-14-00](https://user-images.githubusercontent.com/65212848/81904252-51b1f580-95c3-11ea-8f8f-8692ae6a9003.png)
![Screenshot from 2020-05-14 09-13-37](https://user-images.githubusercontent.com/65212848/81904257-524a8c00-95c3-11ea-98c5-df8babed9a85.png)

**Comment by mitelg** [comment]
@wexoaer if you are in the specific module, that is correct.

but if your are on the dashboard, you will only see the name

**Comment by wexoaer** [comment]
@mitelg  - Ahh okay :) thanks for pointing me the right direction there :)
