### ISSUE TITLE
All imports with csv files is failing. 

### ISSUE THREAD

**Issue by kabengwa** [shopware/shopware#888]
**Description**  

i want to import my products from one installation to another. however every attempt i make fails. and nothing is logged both in the container and app file.

**Additional context**  
i am using shopware 6.1.5 in a docker container. and am also exporting the products from a server in the same environment and version. When i download and open the failed records this is all i see `SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`label_db_test`.`product_category`` 

Is there something i should know or something am doing wrong?

**Comment by shyim** [comment]
Can you provide the profile and csv?

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
