### ISSUE TITLE
Import CLI Command - Calls export

### ISSUE THREAD

**Issue by AndreasA** [shopware/shopware#941]
**Description**  
Here:
https://github.com/shopware/platform/blob/6.2/src/Core/Content/ImportExport/Command/ImportEntityCommand.php#L92

the command calls export instead of import.

Furthermore, it is not possible to choose the profile through CLI, e.g. by providing a profile ID or profile name.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
