### ISSUE TITLE
Template overwriting broken after updating from 6.1.5 to 6.2

### ISSUE THREAD

**Issue by heydavee** [shopware/shopware#956]
So my theme or "plugin" `base.html.twig` is located here:

`custom/plugins/CustomTheme/src/Resources/views/storefront`

When i use 

`{% sw_extends '@Storefront/storefront/base.html.twig' %}`

and change the base_header module to

```
{% block base_header %}
<h1>Hello World</h1>
{% endblock %} 
```

The changes are not visible. That goes with every overwriting process across the website

How do i fix this? Did i miss something?

**Comment by dominikmank** [comment]
I've had the same problem. For me it was a problem that my theme.json File containing the field "name" didn't match up with the plugin name.
It could'nt extend because it's not found when the template should be resolved in https://github.com/shopware/core/blob/v6.2.0/Framework/Adapter/Twig/TemplateFinder.php#L110 .

Perhaps you've got the same problem?

**Comment by heydavee** [comment]
> I've had the same problem. For me it was a problem that my theme.json File containing the field "name" didn't match up with the plugin name.
> It could'nt extend because it's not found when the template should be resolved in https://github.com/shopware/core/blob/v6.2.0/Framework/Adapter/Twig/TemplateFinder.php#L110 .
> 
> Perhaps you've got the same problem?

In my composer.json i got 

`"name": "swag/theme-skeleton",`

But in my theme.json i got

`"name": "customtheme",`

You think that is the root of the issue?

My css is loaded totally fine by the way.

Also when i double checked the documentation i found that they changed the folder structure or am i missing something here again 😄 

`src/Resources/app/storefront/views/layout/header`

I'm using

`src/Resources/views/storefront/layout/header` for example

I am hella confused . Appreciate all the help

**Comment by mitelg** [comment]
@DaveWoody this is an issue of the docs. your path is correct. also have a look at this PR :wink: 
https://github.com/shopware/platform/pull/857/files

**Comment by dominikmank** [comment]
Sorry, my answer went in the wrong direction. The rebuilding of the views was also part of my problem. But not exclusively. My problem was also that my theme was not found in the InheritanceBuild Process which happened because of the changes from https://github.com/shopware/storefront/commit/7c7f7e4546b5aba1cc118f679f3f830b24980c49.
Maybe it was just too many problems to solve at once ;-)

**Comment by heydavee** [comment]
Fixed. Thanks @dominikmank ! It really was a case-sensitive issue with the name.
I changed it, compiled, cleared cache and everything works again.
