### ISSUE TITLE
Empty snippets so that they don't get overridden by inheritance

### ISSUE THREAD

**Issue by JoshuaBehrens** [shopware/shopware#978]
**Description**  
I want to remove the content of a snippet as it should not be displayed at all. When I have it empty the placeholder is shown. I assume it will fallback to the value from the file. So put in there a space to make it sort-of empty. But the administration does not allow me to save it.

**Possible Solution**  
Allow saving empty snippets and differ between empty and null snippets.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
