### ISSUE TITLE
 Mobile navigation has min-height after returning from the subcategory

### ISSUE THREAD

**Issue by joanna-gil** [shopware/shopware#979]
**Description**  

When the user goes to mobile navigation, clicks on a category, and then returns to the view with all categories, the window height is too large, gets the height from opened subcategories

**Additional context**  
![Screenshot from 2020-05-28 13-02-32](https://user-images.githubusercontent.com/57439261/83133701-8b1a5300-a0e3-11ea-8362-c0abea3b5eb8.png)

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
