### ISSUE TITLE
Offcanvas submenu to small

### ISSUE THREAD

**Issue by NicoWenig27** [shopware/shopware#980]
**Description**  
Prerequisites:
- Enough root-level categories that you can scroll in mobile offcanvas navigation
- One category with only one subcategory at the end of the root-level

If you open the category with only one subcategory while scrolled to the bottom of the offcanvas, the submenu will be smaller than the root menu and you will still see the root menu below it. Furthermore if you have many root categories you will not even notice, that there opened a sub menu, if you don't scroll up manually. The offcanvas should automatically scroll up, if you open a submenu.

**Comment by leptoquark1** [comment]
This Problem still present in Shopware 6.3.x.x. Is this scheduled?

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
