### ISSUE TITLE
Product Cross Selling does not support custom fields

### ISSUE THREAD

**Issue by AndreasA** [shopware/shopware#982]
**Description**  
Add support for custom fields in cross selling. At least the entity itself should have the option to add custom fields (even if the admin does not yet display them).

**Comment by JonasResch99** [comment]
This would be really useful to have. Especially since (as far as I know) every other database entity has a custom_fields column.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
