### ISSUE TITLE
Missing NotBlank Constraint in DateFieldSerialzer

### ISSUE THREAD

**Issue by MrMDeluxe** [shopware/shopware#996]
In my entity definition file i have a date field with added required flag.
This is ignored due to the getContraints function of the DateFieldSerializer, where only a type constraint will be returned.

Possible Solution:
Also add the NotBlank Constraint to the DateFieldSerializer getConstraints function.

Then also mapApiErrors/mapPropertyErrors will work for dateFields in the administration...

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
